human_profession_mapping = {
    (1, 16): "AKOLITA",
    (17, 28): "APTEKARZ",
    (29, 32): "BAGIENNIK",
    (33, 44): "BAJARZ",
    (45, 48): "BALSAMISTA",
    (49, 64): "BANITA",
    (65, 68): "BERSERKER Z NORSKI",
    (69, 80): "BŁĘDNY RYCERZ",
    (81, 88): "BYŁY WIĘZIEŃ",
    (89, 92): "CENOBITA",
    (93, 104): "CHŁOP",
    (105, 112): "CIURA OBOZOWA",
    (113, 128): "CYRKOWIEC",
    (129, 140): "CYRULIK",
    (141, 144): "CZEKISTA",
    (145, 148): "DOKER",
    (149, 160): "DYLETANT",
    (161, 164): "FANATYK",
    (165, 180): "FLISAK",
    (181, 184): "GAZECIARZ",
    (185, 192): "GIERMEK",
    (193, 204): "GLADIATOR",
    (205, 212): "GÓRNIK",
    (213, 220): "GRABARZ",
    (221, 224): "GRABIEŻCA",
    (225, 236): "GUŚLARZ",
    (237, 244): "HANDLARZ KOŃMI",
    (245, 256): "HIENA CMENTARNA",
    (257, 260): "KADET",
    (261, 276): "KANCIARZ",
    (277, 284): "KARTOGRAF",
    (285, 288): "KOCZOWNIK",
    (289, 300): "KOMINIARZ",
    (301, 304): "KORSARZ",
    (305, 312): "KOZAK KISLEVSKI",
    (313, 320): "LATARNIK",
    (321, 332): "LEŚNIK",
    (333, 344): "ŁOWCA",
    (345, 356): "ŁOWCA NAGRÓD",
    (357, 368): "MIESZCZANIN",
    (369, 372): "MYTNIK",
    (373, 388): "NAJEMNIK",
    (389, 392): "NIEWOLNIK",
    (393, 404): "OCHOTNIK",
    (405, 420): "OCHRONIARZ",
    (421, 432): "OPRYCH",
    (433, 444): "PACHOŁEK",
    (445, 448): "PASTERZ Z CARCASONNE",
    (449, 456): "PAŹ",
    (457, 468): "PIELGRZYM",
    (469, 476): "PIELGRZYM GRAALA",
    (477, 480): "PIRAT RZECZNY",
    (481, 492): "PODŻEGACZ",
    (493, 500): "POGANIACZ BYDŁA",
    (501, 508): "POGANIACZ MUŁÓW",
    (509, 516): "POGRANICZNIK",
    (517, 520): "POKUTNIK",
    (521, 528): "PORYWACZ ZWŁOK",
    (529, 536): "POSKRAMIACZ NIEDŹWIEDZI",
    (537, 544): "POSŁANIEC",
    (545, 548): "PRAWNIK",
    (549, 556): "PRZEMYTNIK",
    (557, 564): "PRZEPATRYWACZ",
    (565, 572): "PRZEWOŹNIK",
    (573, 576): "PUSTELNIK",
    (577, 580): "ROGATY ŁOWCA",
    (581, 592): "ROLNIK",
    (593, 596): "ROZJEMCA",
    (597, 608): "RYBAK",
    (609, 624): "RZEMIEŚLNIK",
    (625, 636): "RZEZIMIESZEK",
    (637, 640): "SKALD",
    (641, 652): "SKARBNIK",
    (653, 664): "SKRYBA",
    (665, 672): "SŁUGA",
    (673, 684): "STRAŻNIK",
    (685, 700): "STRAŻNIK DRÓG",
    (701, 708): "STRAŻNIK KANAŁÓW",
    (709, 716): "STRAŻNIK RZECZNY",
    (717, 720): "STRAŻNIK ŚWIĄTYNNY",
    (721, 724): "STRAŻNIK TUNELI",
    (725, 732): "STRAŻNIK WIĘZIENNY",
    (733, 736): "STRELTSI",
    (737, 740): "STRZYGAŃSKI MISTYK",
    (741, 760): "SZCZUROŁAP",
    (761, 772): "SZEPTUCHA",
    (773, 776): "SZERMIERZ ESTALIJSKI",
    (777, 792): "SZLACHCIC",
    (793, 796): "SZPERACZ",
    (797, 808): "SZULER",
    (809, 816): "ŚMIECIARZ",
    (817, 824): "UCZENNICA LODOWEJ WIEDŹMY",
    (825, 840): "UCZEŃ CZARODZIEJA",
    (841, 848): "UCZEŃ GUŚLARZA",
    (849, 856): "WĘGLARZ",
    (857, 864): "WIELORYBNIK",
    (865, 872): "WŁÓCZYKIJ",
    (873, 876): "WOJ",
    (877, 888): "WOŹNICA",
    (889, 896): "WRÓŻBITA",
    (897, 904): "ZAKAPTURZONY",
    (905, 916): "ZARZĄDCA",
    (917, 924): "ZBIERACZ ŁAJNA",
    (925, 940): "ZŁODZIEJ",
    (941, 948): "ŻABIARKA",
    (949, 960): "ŻAK",
    (961, 972): "ŻEGLARZ",
    (973, 984): "ŻOŁNIERZ",
    (985, 1000): "ŻOŁNIERZ OKRĘTOWY",
}
halfling_profession_mapping = {
    (1, 13): "AKOLITA",
    (14, 26): "APTEKARZ",
    (27, 55): "BAJARZ",
    (56, 62): "BALSAMISTA",
    (63, 82): "BANITA",
    (83, 89): "BYŁY WIĘZIEŃ",
    (90, 114): "CHŁOP",
    (115, 127): "CIURA OBOZOWA",
    (128, 147): "CYRKOWIEC",
    (148, 154): "CYRULIK",
    (155, 174): "DYLETANT",
    (175, 194): "GAZECIARZ",
    (195, 201): "GRABARZ",
    (202, 225): "HIENA CMENTARNA",
    (226, 258): "KANCIARZ",
    (259, 271): "KARTOGRAF",
    (272, 304): "KOMINIARZ",
    (305, 317): "LATARNIK",
    (318, 350): "ŁOWCA",
    (351, 363): "ŁOWCA NAGRÓD",
    (364, 376): "MIESZCZANIN",
    (377, 389): "MYTNIK",
    (390, 414): "NAJEMNIK",
    (415, 421): "NIEWOLNIK",
    (422, 446): "OCHOTNIK",
    (447, 449): "OPRYCH",
    (450, 469): "PAŹ",
    (470, 482): "PIELGRZYM",
    (483, 502): "PODŻEGACZ",
    (503, 509): "POGANIACZ MUŁÓW",
    (510, 516): "POGRANICZNIK",
    (517, 546): "PORYWACZ ZWŁOK",
    (547, 579): "POSŁANIEC",
    (580, 592): "PRAWNIK",
    (593, 612): "PRZEMYTNIK",
    (613, 619): "PRZEWOŹNIK",
    (620, 632): "ROLNIK",
    (633, 645): "RYBAK",
    (646, 687): "RZEMIEŚLNIK",
    (688, 694): "SKARBNIK",
    (695, 707): "SKRYBA",
    (708, 745): "SŁUGA",
    (746, 769): "STRAŻNIK",
    (770, 782): "STRAŻNIK KANAŁÓW",
    (783, 815): "STRAŻNIK PÓL",
    (816, 828): "STRAŻNIK ŚWIĄTYNNY",
    (829, 838): "SZCZUROŁAP",
    (839, 851): "SZLACHCIC",
    (852, 864): "SZULER",
    (865, 871): "ŚMIECIARZ",
    (872, 891): "WĘGLARZ",
    (892, 916): "WŁÓCZYKIJ",
    (917, 929): "ZARZĄDCA",
    (930, 936): "ZBIERACZ ŁAJNA",
    (937, 974): "ZŁODZIEJ",
    (975, 987): "ŻAK",
    (988, 1000): "ŻOŁNIERZ",
}
dwarf_profession_mapping = {
    (1, 15): "AKOLITA",
    (16, 30): "BAJARZ",
    (31, 51): "BANITA",
    (52, 66): "BYŁY WIĘZIEŃ",
    (67, 87): "CYRKOWIEC",
    (88, 129): "CZELADNIK RUN",
    (130, 144): "DOKER",
    (145, 159): "DYLETANT",
    (160, 194): "GLADIATOR",
    (195, 229): "GONIEC",
    (230, 271): "GÓRNIK",
    (272, 292): "HIENA CMENTARNA",
    (293, 320): "KANCIARZ",
    (321, 335): "KARTOGRAF",
    (336, 363): "ŁOWCA",
    (364, 378): "ŁOWCA NAGRÓD",
    (379, 399): "MIESZCZANIN",
    (400, 414): "MYTNIK",
    (415, 456): "NAJEMNIK",
    (457, 464): "NIEWOLNIK",
    (465, 492): "OCHOTNIK",
    (493, 520): "OCHRONIARZ",
    (521, 535): "OPRYCH",
    (536, 550): "PIELGRZYM",
    (551, 565): "PODŻEGACZ",
    (566, 586): "POGANIACZ MUŁÓW",
    (587, 607): "PRZEMYTNIK",
    (608, 635): "RZEMIEŚLNIK",
    (636, 663): "RZEZIMIESZEK",
    (664, 678): "SKRYBA",
    (679, 693): "SŁUGA",
    (694, 713): "STRAŻNIK",
    (714, 728): "STRAŻNIK KANAŁÓW",
    (729, 743): "STRAŻNIK ŚWIĄTYNNY",
    (744, 771): "STRAŻNIK WIĘZIENNY",
    (772, 799): "SZCZUROŁAP",
    (800, 814): "SZLACHCIC",
    (815, 829): "SZULER",
    (830, 857): "TARCZOWNIK",
    (858, 885): "WŁÓCZYKIJ",
    (886, 900): "WOŹNICA",
    (901, 928): "ZABÓJCA TROLLI",
    (929, 949): "ZŁODZIEJ",
    (950, 964): "ŻAK",
    (965, 972): "ŻEGLARZ",
    (973, 1000): "ŻOŁNIERZ",
}
elf_profession_mapping = {
    (1, 7): "APTEKARZ",
    (8, 64): "UCZEŃ CZARODZIEJA",
    (65, 78): "OCHRONIARZ",
    (79, 99): "ŁOWCA NAGRÓD",
    (100, 113): "KARTOGRAF",
    (114, 141): "DYLETANT",
    (142, 176): "CYRKOWIEC",
    (177, 218): "RZECZNIK RODU",
    (219, 222): "SZULER",
    (223, 278): "ŁOWCA",
    (279, 292): "AKOLITA",
    (293, 342): "WOJOWNIK KLANOWY",
    (343, 377): "ŻOŁNIERZ OKRĘTOWY",
    (378, 412): "NAJEMNIK",
    (413, 450): "POSŁANIEC",
    (451, 464): "SZLACHCIC",
    (465, 494): "BANITA",
    (495, 534): "PRZEPATRYWACZ",
    (535, 548): "PIELGRZYM",
    (549, 562): "GLADIATOR",
    (563, 600): "BAJARZ",
    (601, 625): "STRAŻNIK RZECZNY",
    (626, 665): "KANCIARZ",
    (666, 705): "SKRYBA",
    (706, 745): "ŻEGLARZ",
    (746, 752): "NIEWOLNIK",
    (753, 780): "PRZEMYTNIK",
    (781, 815): "ŻAK",
    (816, 856): "ZŁODZIEJ",
    (857, 869): "OPRYCH",
    (870, 919): "RZEMIEŚLNIK",
    (920, 961): "WŁÓCZYKIJ",
    (962, 1000): "LEŚNIK",
}
halfling_ability_mapping = {
    (1, 4): "bardzo silny",
    (5, 9): "bardzo szybki",
    (10, 13): "błyskotliwość",
    (14, 18): "bystry wzrok",
    (19, 23): "charyzmatyczny",
    (24, 28): "czuły słuch",
    (29, 34): "geniusz arytmetyczny",
    (35, 39): "krzepki",
    (40, 44): "naśladowca",
    (45, 49): "niezwykle odporny",
    (50, 53): "oburęczność",
    (54, 58): "odporność na choroby",
    (59, 62): "odporność na magię",
    (63, 64): "odporność na trucizny",
    (65, 68): "odporność psychiczna",
    (69, 73): "opanowanie",
    (74, 78): "strzelec wyborowy",
    (79, 82): "szczęście",
    (83, 87): "szósty zmysł",
    (88, 92): "szybki refleks",
    (93, 96): "twardziel",
    (97, 100): "urodzony wojownik",
}
human_ability_mapping = {
    (1, 4): "bardzo silny",
    (5, 9): "bardzo szybki",
    (10, 13): "błyskotliwość",
    (14, 18): "bystry wzrok",
    (19, 22): "charyzmatyczny",
    (23, 27): "czuły słuch",
    (28, 31): "geniusz arytmetyczny",
    (32, 35): "krzepki",
    (36, 40): "naśladowca",
    (41, 44): "niezwykle odporny",
    (45, 49): "oburęczność",
    (50, 53): "odporność na choroby",
    (54, 57): "odporność na magię",
    (58, 61): "odporność na trucizny",
    (62, 66): "odporność psychiczna",
    (67, 71): "opanowanie",
    (72, 75): "strzelec wyborowy",
    (76, 79): "szczęście",
    (80, 83): "szósty zmysł",
    (84, 87): "szybki refleks",
    (88, 91): "twardziel",
    (92, 95): "urodzony wojownik",
    (96, 100): "widzenie w ciemności",
}
ability_modify_attr = {
    "urodzony wojownik": "WW",
    "strzelec wyborowy": "US",
    "bardzo silny": "K",
    "niezywkle odporny": "Odp",
    "szybki refleks": "Zr",
    "błyskotliwość": "Int",
    "opanowanie": "SW",
    "charyzmatyczny": "Ogd",
    "twardziel": "Żyw",
    "bardzo szybki": "Sz",
}
# dwarf weight as common
common_weight_mapping = {
    (1, 1): 45,
    (2, 10): 50,
    (11, 20): 55,
    (21, 30): 60,
    (31, 40): 65,
    (41, 50): 70,
    (51, 60): 75,
    (61, 70): 80,
    (71, 80): 85,
    (81, 90): 90,
    (91, 99): 95,
    (100, 100): 100,
}
halfling_weight_mapping = {
    (1, 1): 35,
    (2, 10): 35,
    (11, 20): 40,
    (21, 30): 40,
    (31, 40): 45,
    (41, 50): 45,
    (51, 60): 50,
    (61, 70): 50,
    (71, 80): 55,
    (81, 90): 60,
    (91, 99): 65,
    (100, 100): 70,
}
human_hair_list = [
    "Popielaty",
    "Ciemny blond",
    "Blond",
    "Rudy",
    "Ciemny rudy",
    "Jasnobrązowy",
    "Brązowy",
    "Brązowy",
    "Ciemnobrązowy",
    "Czarny",
]
halfling_hair_list = [
    "Popielaty",
    "Ciemny blond",
    "Blond",
    "Blond",
    "Rudy",
    "Ciemny rudy",
    "Jasnobrązowy",
    "Brązowy",
    "Ciemnobrązowy",
    "Czarny",
]
dwarf_hair_list = [
    "Popielaty",
    "Blond",
    "Ciemny rudy",
    "Czerowny",
    "Rudy",
    "Brązowy",
    "Brązowy",
    "Ciemnobrązowy",
    "Czarny",
    "Kruczoczarny",
]
elf_hair_list = [
    "Srebrny",
    "Biały",
    "Jasny blond",
    "Ciemny blond",
    "Miedziany",
    "Jasnobrązowy",
    "Kasztanowy",
    "Brązowy",
    "Ciemnobrązowy",
    "Czarny",
]
human_eye_list = [
    "Szary",
    "Ciemnoniebieski",
    "Niebieski",
    "Zielony",
    "Piwny",
    "Jasnobrązowy",
    "Brązowy",
    "Ciemnobrązowy",
    "Fioletowy",
    "Czarny",
]
halfling_eye_list = [
    "Niebieski",
    "Orzechowy",
    "Orzechowy",
    "Jasnobrązowy",
    "Jasnobrązowy",
    "Brązowy",
    "Brązowy",
    "Ciemnobrązowy",
    "Ciemnobrązowy",
    "Ciemnobrązowy",
]
dwarf_eye_list = [
    "Szary",
    "Ciemnoniebieski",
    "Piwny",
    "Jasnobrązowy",
    "Jasnobrązowy",
    "Brązowy",
    "Brązowy",
    "Ciemnobrązowy",
    "Ciemnobrązowy",
    "Fioletowy",
]
elf_eye_list = [
    "Szaroniebieski",
    "Niebieski",
    "Zielony",
    "Orzechowy",
    "Kasztanowy",
    "Brązowy",
    "Ciemnobrązowy",
    "Srebrny",
    "Fioletowy",
    "Czarny",
]
special_mapping = {
    (1, 5): "Bielmo na oku",
    (6, 10): "Blizna",
    (11, 15): "Brak brwi",
    (16, 20): "Brak palca",
    (21, 25): "Brak zęba",
    (26, 29): "Brodawki",
    (30, 35): "Blada cera",
    (36, 39): "Duży nos",
    (40, 45): "Duży pieprzyk",
    (46, 50): "Dziwny zapach ciała",
    (51, 55): "Kolczyk w nosie",
    (56, 60): "Kolczyk w uchu",
    (61, 65): "Niewielka łysina",
    (66, 70): "Oczy różnego koloru",
    (71, 75): "Piegi",
    (76, 80): "Poszarpane ucho",
    (81, 84): "Ślady po ospie",
    (85, 89): "Tatuaż",
    (90, 94): "Wystające zęby",
    (95, 98): "Wytrzeszczone oczy",
    (99, 100): "Złamany nos",
}
# halfling siblings = human siblings + 1
siblings_human_mapping = {
    (1, 1): 0,
    (2, 3): 1,
    (4, 5): 2,
    (6, 7): 3,
    (8, 9): 4,
    (10, 10): 5,
}
siblings_dwarf_mapping = {(1, 3): 0, (4, 7): 1, (8, 9): 2, (10, 10): 3}
siblings_elf_mapping = {(1, 1): 0, (2, 5): 1, (6, 9): 2, (10, 10): 3}
star_mapping = {
    (1, 5): "Bębniarz",
    (6, 10): "Dudy",
    (11, 15): "Dwa Byki",
    (16, 25): "Głupiec Mummit",
    (26, 30): "Gwiazda Uroku",
    (31, 35): "Gwiazda Wieczorna",
    (36, 40): "Kocioł Rhyi",
    (41, 45): "Lancet",
    (46, 50): "Mędrzec Mammit",
    (51, 55): "Pas Grungniego",
    (56, 60): "Rozbity Wóz",
    (61, 65): "Smok Dragomas",
    (66, 70): "Sznur Limnera",
    (71, 75): "Tancerka",
    (76, 80): "Tłusty Kozioł",
    (81, 85): "Vobist Ulotny",
    (86, 90): "Wielki Krzyż",
    (91, 95): "Wół Gnuthus",
    (96, 98): "Wymund Pustelnik",
    (99, 100): "Złoty Kogut",
}
# human names lists only contain imperial names
human_female_name_list = [
    "Abbie",
    "Abighild",
    "Abigund",
    "Abigunda",
    "Ada",
    "Ada",
    "Adel",
    "Adelind",
    "Adeline",
    "Adelyn",
    "Adelle",
    "Agathe",
    "Agnete",
    "Aldreda",
    "Alfreda",
    "Alicia",
    "Allane",
    "Althea",
    "Amalie",
    "Amalinde",
    "Amalyn",
    "Anhilda",
    "Annabella",
    "Anna",
    "Anthea",
    "Arabella",
    "Aver",
    "Bechilda",
    "Bella",
    "Bella",
    "Bellane",
    "Benedicta",
    "Berlinda",
    "Berlyn",
    "Bertha",
    "Berthilda",
    "Bess",
    "Bess",
    "Beth",
    "Broncea",
    "Brunhilda",
    "Camilla",
    "Carla",
    "Carlinda",
    "Carlotta",
    "Cilicia",
    "Cilie",
    "Clora",
    "Clothilda",
    "Connie",
    "Constance",
    "Constanza",
    "Cordelia",
    "Dema",
    "Demona",
    "Desdemona",
    "Dorthilda",
    "Drachena",
    "Drachilda",
    "Edhilda",
    "Edith",
    "Edyth",
    "Edythe",
    "Eleanor",
    "Eleanor",
    "Elinor",
    "Elisinda",
    "Elsina",
    "Ella",
    "Ellene",
    "Ellinde",
    "Eloise",
    "Elsa",
    "Elsa",
    "Elsbeth",
    "Elspeth",
    "Elyn",
    "Emagunda",
    "Emelia",
    "Emme",
    "Emmalyn",
    "Emmanuel",
    "Emerlinde",
    "Emerlyn",
    "Erica",
    "Ermina",
    "Erminlind",
    "Esmeralda",
    "Estelle",
    "Etheldreda",
    "Ethelind",
    "Ethelreda",
    "Fay",
    "Frieda",
    "Frieda",
    "Friedhilda",
    "Friedrun",
    "Friedrica",
    "Gabby",
    "Gabby",
    "Gabriele",
    "Galina",
    "Gena",
    "Genevieve",
    "Genoveva",
    "Gerberga",
    "Gerda",
    "Gerlinde",
    "Gertie",
    "Gertrud",
    "Greta",
    "Greta",
    "Gretchen",
    "Grizelda",
    "Grunhilda",
    "Gudrun",
    "Gudryn",
    "Hanna",
    "Hedwig",
    "Heidi",
    "Heidrun",
    "Helga",
    "Herlinde",
    "Herwig",
    "Hilda",
    "Hilda",
    "Hildegart",
    "Hildegund",
    "Honoria",
    "Ida",
    "Ingrid",
    "Ingrun",
    "Ingrund",
    "Irmella",
    "Irmine",
    "Isabella",
    "Isadora",
    "Isolde",
    "Isolde",
    "Jocelin",
    "Johanna",
    "Josie",
    "Karin",
    "Katarine",
    "Katheryn",
    "Katharina",
    "Katerine",
    "Katerine",
    "Keterlind",
    "Keterlyn",
    "Kitty",
    "Kristen",
    "Kristena",
    "Kristyn",
    "Kirsten",
    "Kirsten",
    "Kirstyn",
    "Lavina",
    "Lavinia",
    "Leanor",
    "Leanora",
    "Leticia",
    "Letty",
    "Lena",
    "Lenora",
    "Lisa",
    "Lisbeth",
    "Lizzie",
    "Lorinda",
    "Lorna",
    "Lucinda",
    "Lucretia",
    "Lucie",
    "Ludmilla",
    "Mabel",
    "Madge",
    "Magdalyn",
    "Maggie",
    "Maghilda",
    "Maglind",
    "Maglyn",
    "Magunda",
    "Magreta",
    "Maida",
    "Marien",
    "Marietta",
    "Margaret",
    "Marget",
    "Margreta",
    "Marline",
    "Marlyn",
    "Mathilda",
    "Maude",
    "May",
    "Meg",
    "Melicent",
    "Miranda",
    "Moll",
    "Nathilda",
    "Nellie",
    "Nellie",
    "Nora",
    "Nora",
    "Olga",
    "Olga",
    "Ophelia",
    "Ophelia",
    "Osterhild",
    "Osterhild",
    "Ostelle",
    "Ostelle",
    "Ostia",
    "Ostia",
    "Ottagunda",
    "Ottagunda",
    "Ottaline",
    "Ottaline",
    "Ottilda",
    "Ottilda",
    "Ottilyn",
    "Ottilyn",
    "Perdita",
    "Perdita",
    "Pergale",
    "Pergale",
    "Pergunda",
    "Pergunda",
    "Petronella",
    "Petronella",
    "Philomelia",
    "Philomelia",
    "Reikhilda",
    "Reikhilda",
    "Renata",
    "Renata",
    "Rosabel",
    "Rosabel",
    "Rosabella",
    "Rosabella",
    "Rosale",
    "Rosale",
    "Rosalia",
    "Rosalia",
    "Rosalin",
    "Rosalin",
    "Rosalinde",
    "Rosalinde",
    "Rosamunde",
    "Rosamunde",
    "Rosanne",
    "Rosanne",
    "Rose",
    "Rose",
    "Roz",
    "Roz",
    "Rozhilda",
    "Rozhilda",
    "Salina",
    "Salina",
    "Saltza",
    "Saltza",
    "Sigismunda",
    "Sigrid",
    "Sigrid",
    "Sigunda",
    "Sigunda",
    "Solla",
    "Solla",
    "Styrine",
    "Styrine",
    "Talima",
    "Talima",
    "Theodora",
    "Theodora",
    "Therese",
    "Therese",
    "Tilea",
    "Tilea",
    "Ursula",
    "Ursula",
    "Ulrica",
    "Ulrica",
    "Valeria",
    "Valeria",
    "Verena",
    "Verena",
    "Wilfrieda",
    "Wilfrieda",
    "Wilhelmina",
    "Wilhelmina",
    "Winifred",
    "Winifred",
    "Wolfhilde",
    "Wolfhilde",
    "Zemelda",
    "Zemelda",
    "Zena",
]
human_male_name_list = [
    "Abelhard",
    "Abelhelm",
    "Admund",
    "Adred",
    "Adric",
    "Agis",
    "Alaric",
    "Alberic",
    "Albrecht",
    "Aldebrand",
    "Aldred",
    "Aldric",
    "Alfreid",
    "Altmar",
    "Alric",
    "Andre",
    "Andred",
    "Andric",
    "Anshelm",
    "Anton",
    "Arne",
    "Arnulf",
    "Axel",
    "Axelbrand",
    "Baldred",
    "Baldric",
    "Baldwin",
    "Balthasar",
    "Barnabas",
    "Bart",
    "Bartolf",
    "Bartomar",
    "Bernolt",
    "Bertold",
    "Bertolf",
    "Boris",
    "Bruno",
    "Burgolf",
    "Calvin",
    "Casimir",
    "Caspar",
    "Cedred",
    "Conrad",
    "Corvin",
    "Dagmar",
    "Dankmar",
    "Dankred",
    "Dekmar",
    "Detlef",
    "Diebold",
    "Diel",
    "Dietfried",
    "Dieter",
    "Dietmar",
    "Dietmund",
    "Dietrich",
    "Dirk",
    "Donat",
    "Durnhelm",
    "Eber",
    "Eckel",
    "Eckhart",
    "Edgar",
    "Edmund",
    "Edwin",
    "Ehrhart",
    "Ehrl",
    "Ehrwig",
    "Eldred",
    "Elmeric",
    "Emil",
    "Engel",
    "Engelbert",
    "Engelbrecht",
    "Engelhart",
    "Eodred",
    "Eomund",
    "Erdman",
    "Erdred",
    "Erkenbrand",
    "Erasmus",
    "Erich",
    "Erman",
    "Ernst",
    "Erwin",
    "Eugen",
    "Eustasius",
    "Ewald",
    "Fabian",
    "Faustus",
    "Felix",
    "Ferdinand",
    "Fleugweiner",
    "Fosten",
    "Franz",
    "Frediger",
    "Frederic",
    "Friebald",
    "Friedrich",
    "Gawin",
    "Gerber",
    "Gerhart",
    "Gerlach",
    "Gernar",
    "Gerolf",
    "Gilbrecht",
    "Gisbert",
    "Giselbrecht",
    "Gismar",
    "Goran",
    "Gosbert",
    "Goswin",
    "Gotfried",
    "Gothard",
    "Gottolf",
    "Gotwin",
    "Gregor",
    "Greimold",
    "Grimwold",
    "Griswold",
    "Guido",
    "Gundolf",
    "Gundred",
    "Gunnar",
    "Gunter",
    "Gunther",
    "Gustaf",
    "Hadred",
    "Hadwin",
    "Hagar",
    "Hagen",
    "Haldred",
    "Halman",
    "Hamlyn",
    "Hans",
    "Harbrand",
    "Harman",
    "Hartmann",
    "Haug",
    "Heidric",
    "Heimar",
    "Heinfried",
    "Heinman",
    "Heinrich",
    "Heinz",
    "Helmut",
    "Henlyn",
    "Hermann",
    "Herwin",
    "Hieronymus",
    "Hildebart",
    "Hildebrand",
    "Hildemar",
    "Hildemund",
    "Hildred",
    "Hildric",
    "Horst",
    "Hugo",
    "Igor",
    "Ingwald",
    "Jander",
    "Jekil",
    "Jodokus",
    "Johann",
    "Jonas",
    "Jorg",
    "Jorn",
    "Josef",
    "Jost",
    "Jurgen",
    "Karl",
    "Kaspar",
    "Klaus",
    "Kleber",
    "Konrad",
    "Konradin",
    "Kurt",
    "Lamprecht",
    "Lanfried",
    "Lanric",
    "Lanwin",
    "Leo",
    "Leopold",
    "Levin",
    "Liebert",
    "Liebrecht",
    "Liebwin",
    "Lienhart",
    "Linus",
    "Lodwig",
    "Lothar",
    "Lucius",
    "Ludwig",
    "Luitpold",
    "Lukas",
    "Lupold",
    "Lupus",
    "Luther",
    "Lutolf",
    "Madred",
    "Magnus",
    "Mandred",
    "Manfred",
    "Mathias",
    "Max",
    "Maximillian",
    "Meiner",
    "Meinhart",
    "Meinolf",
    "Mekel",
    "Merkel",
    "Nat",
    "Nathandar",
    "Nicodemus",
    "Odamar",
    "Odric",
    "Odwin",
    "Olbrecht",
    "Oldred",
    "Oldric",
    "Ortlieb",
    "Ortolf",
    "Orwin",
    "Oswald",
    "Osric",
    "Oswin",
    "Otfried",
    "Otto",
    "Otwin",
    "Paulus",
    "Prospero",
    "Ragen",
    "Ralf",
    "Rambrecht",
    "Randulf",
    "Ranulf",
    "Ranald",
    "Reikhard",
    "Rein",
    "Reiner",
    "Reinhard",
    "Reinolt",
    "Reuban",
    "Rigo",
    "Roderic",
    "Rolf",
    "Ruben",
    "Rudel",
    "Rudgar",
    "Rudolf",
    "Rufus",
    "Ruprecht",
    "Sebastian",
    "Semund",
    "Sepp",
    "Sieger",
    "Siegfried",
    "Siegmund",
    "Sigismund",
    "Sigric",
    "Steffan",
    "Tankred",
    "Theoderic",
    "Tilmann",
    "Tomas",
    "Trubald",
    "Trubert",
    "Udo",
    "Ulli",
    "Ulfred",
    "Ulfman",
    "Ulman",
    "Uto",
    "Valdred",
    "Valdric",
    "Varl",
    "Viggo",
    "Viktor",
    "Vilmar",
    "Volker",
    "Volkhard",
    "Volkrad",
    "Volkin",
    "Voltz",
    "Walbrecht",
    "Waldor",
    "Waldred",
    "Walther",
    "Warmund",
    "Werner",
    "Wilbert",
    "Wilfried",
    "Wilhelm",
    "Woldred",
    "Wolfram",
    "Wolfhart",
    "Wolfgang",
    "Wulf",
    "Xavier",
]
# dwarf name = name1M/F + name2M/F
dwarf_name1_list = [
    "Al",
    "Ath",
    "Althran",
    "Bal",
    "Bala",
    "Bara",
    "Bel",
    "Bela",
    "Ber",
    "Bok",
    "Bor",
    "Bur",
    "Da",
    "Dam",
    "Dora",
    "Drok",
    "Drong",
    "Dur",
    "Dwal",
    "El",
    "Ela",
    "Elan",
    "Elda",
    "Fa",
    "Far",
    "Fara",
    "Fim",
    "Fima",
    "Firen",
    "Fur",
    "Fura",
    "Ga",
    "Gim",
    "Gol",
    "Gollen",
    "Got",
    "Gota",
    "Grim",
    "Gro",
    "Grun",
    "Hak",
    "Haka",
    "Har",
    "Hega",
    "Hur",
    "Kad",
    "Kar",
    "Kata",
    "Kaz",
    "Kaza",
    "Krag",
    "Logaz",
    "Lok",
    "Lun",
    "Mo",
    "Mola",
    "Mor",
    "Mora",
    "No",
    "Nola",
    "Nor",
    "Noran",
    "Nun",
    "Oda",
    "Oka",
    "Olla",
    "Olf",
    "Oth",
    "Othra",
    "Ro",
    "Ror",
    "Roran",
    "Ska",
    "Skalla",
    "Skalf",
    "Skar",
    "Skor",
    "Skora",
    "Snor",
    "Snora",
    "Sven",
    "Thar",
    "Thor",
    "Thora",
    "Thron",
    "Thrun",
    "Thura",
    "Un",
    "Utha",
    "Ulla",
    "Vala",
    "Var",
    "Vara",
    "Zak",
    "Zaka",
    "Zakan",
    "Zar",
    "Zara",
    "Zam",
    "Zama",
]
dwarf_female_name2_list = [
    "bina",
    "bina",
    "bora",
    "bora",
    "dila",
    "dina",
    "dina",
    "dokina",
    "dokina",
    "dora",
    "dora",
    "drinella",
    "fina",
    "fina",
    "fya",
    "fya",
    "gana",
    "gana",
    "gara",
    "gara",
    "gella",
    "gella",
    "gina",
    "groma",
    "groma",
    "grondella",
    "grondella",
    "grotha",
    "grotha",
    "gruma",
    "gruma",
    "grunda",
    "grunda",
    "gruntina",
    "gruntina",
    "gona",
    "gora",
    "gora",
    "grimella",
    "grimella",
    "grina",
    "grina",
    "gromina",
    "gromina",
    "gula",
    "gunella",
    "gunella",
    "gundina",
    "gundina",
    "kina",
    "kina",
    "kragella",
    "kragella",
    "krina",
    "krina",
    "kya",
    "kya",
    "lina",
    "lina",
    "likina",
    "likina",
    "loka",
    "loka",
    "luna",
    "mina",
    "mina",
    "mira",
    "mira",
    "nina",
    "nina",
    "nira",
    "nira",
    "nya",
    "ragina",
    "ragina",
    "riga",
    "riga",
    "riga",
    "rika",
    "rika",
    "rina",
    "rina",
    "runa",
    "runa",
    "runella",
    "runella",
    "skina",
    "skina",
    "skinella",
    "skinella",
    "tina",
    "toka",
    "trekella",
    "trekella",
    "trekina",
    "trekina",
    "troka",
    "troka",
    "zina",
    "zora",
]
dwarf_male_name2_list = [
    "bin",
    "bin",
    "bor",
    "bor",
    "dil",
    "din",
    "din",
    "dok",
    "dok",
    "dor",
    "dor",
    "drin",
    "drin",
    "fin",
    "fin",
    "gan",
    "gan",
    "gar",
    "gar",
    "gil",
    "gil",
    "gin",
    "gni",
    "gni",
    "grom",
    "grom",
    "grond",
    "grond",
    "groth",
    "groth",
    "grum",
    "grum",
    "grund",
    "grund",
    "grunt",
    "gon",
    "gon",
    "gor",
    "gor",
    "grim",
    "girm",
    "grin",
    "grin",
    "grom",
    "grom",
    "gul",
    "gul",
    "gun",
    "gun",
    "gund",
    "gund",
    "ki",
    "ki",
    "kin",
    "kin",
    "krag",
    "krag",
    "kri",
    "kri",
    "krin",
    "krin",
    "li",
    "li",
    "lin",
    "lin",
    "lik",
    "lik",
    "lok",
    "lok",
    "lun",
    "lun",
    "min",
    "min",
    "mir",
    "mir",
    "nin",
    "nin",
    "nir",
    "nir",
    "rag",
    "ri",
    "ri",
    "rig",
    "rig",
    "rik",
    "rik",
    "rin",
    "rin",
    "run",
    "run",
    "skin",
    "tin",
    "tin",
    "tok",
    "trek",
    "trok",
    "zin",
    "zor",
    "zor",
]
# elf name = name1 + connector(optional) + name2M/F
elf_name1_list = [
    "Aed",
    "Ael",
    "Aelf",
    "Aen",
    "Aeth",
    "Alth",
    "An",
    "And",
    "Ar",
    "Arg",
    "Ast",
    "Ath",
    "Av",
    "Ban",
    "Bel",
    "Beth",
    "Cad",
    "Cael",
    "Caem",
    "Caeth",
    "Cal",
    "Cam",
    "Cel",
    "Cir",
    "El",
    "Eld",
    "Elth",
    "En",
    "End",
    "Er",
    "Ers",
    "Fand",
    "Fer",
    "Ferg",
    "Fim",
    "Fin",
    "Gal",
    "Gald",
    "Gaen",
    "Gaes",
    "Ged",
    "Gen",
    "Ges",
    "Geth",
    "Glor",
    "Has",
    "Hath",
    "Hel",
    "Heth",
    "Hith",
    "Ill",
    "Ind",
    "Ist",
    "Ith",
    "Iy",
    "Kor",
    "Ky",
    "Kyr",
    "La",
    "Lan",
    "Lil",
    "Lim",
    "Lith",
    "Loth",
    "Mal",
    "Mar",
    "Mas",
    "Math",
    "Me",
    "Mes",
    "Meth",
    "Men",
    "Mor",
    "Mort",
    "Nal",
    "Nar",
    "Nen",
    "Nor",
    "Norl",
    "Ri",
    "Riabb",
    "Riann",
    "Rid",
    "Riell",
    "Rien",
    "Ruth",
    "Ryn",
    "Tab",
    "Tal",
    "Tan",
    "Tar",
    "Teth",
    "Tel",
    "Tor",
    "Ty",
    "Ul",
    "Um",
    "Ur",
    "Yr",
    "Yv",
]
elf_name_connector_list = [
    "a",
    "al",
    "an",
    "ar",
    "as",
    "e",
    "el",
    "en",
    "er",
    "es",
    "fan",
    "fen",
    "fin",
    "i",
    "il",
    "in",
    "ir",
    "is",
    "o",
    "ol",
    "on",
    "or",
    "os",
    "ra",
    "ral",
    "ran",
    "re",
    "rel",
    "ren",
    "ri",
    "ril",
    "rin",
    "ro",
    "rol",
    "ron",
    "ry",
    "sa",
    "sal",
    "san",
    "se",
    "sel",
    "sen",
    "si",
    "sil",
    "sin",
    "so",
    "sol",
    "son",
    "u",
    "ul",
]
elf_male_name2_list = [
    "baen",
    "baine",
    "baire",
    "bar",
    "bhir",
    "brier",
    "brior",
    "brin",
    "daen",
    "daine",
    "daire",
    "dar",
    "dhil",
    "dhir",
    "drel",
    "drir",
    "dror",
    "eorl",
    "eos",
    "eoth",
    "fil",
    "fin",
    "fir",
    "hil",
    "hin",
    "hir",
    "hor",
    "il",
    "in",
    "ion",
    "ir",
    "is",
    "ith",
    "lael",
    "laen",
    "laer",
    "laine",
    "laire",
    "lan",
    "las",
    "len",
    "les",
    "lil",
    "lin",
    "lir",
    "lis",
    "lor",
    "los",
    "mael",
    "maen",
    "mair",
    "main",
    "mal",
    "mar",
    "mil",
    "min",
    "mir",
    "nael",
    "naen",
    "naer",
    "nail",
    "nair",
    "nal",
    "nan",
    "nar",
    "neal",
    "nean",
    "near",
    "nil",
    "nin",
    "nir",
    "nis",
    "ran",
    "rea",
    "rel",
    "ril",
    "riol",
    "rion",
    "rior",
    "riorl",
    "riorn",
    "rir",
    "ryel",
    "taen",
    "tair",
    "tain",
    "than",
    "thar",
    "thel",
    "thil",
    "thir",
    "thin",
    "thril",
    "thrin",
    "thwe",
    "til",
    "tin",
    "tis",
    "we",
    "yan",
]
elf_female_name2_list = [
    "a",
    "aine",
    "am",
    "ann",
    "arma",
    "arna",
    "arth",
    "ath",
    "beann",
    "bet",
    "beth",
    "brim",
    "brys",
    "deann",
    "det",
    "deth",
    "dys",
    "drian",
    "driel",
    "drys",
    "eann",
    "eanna",
    "earna",
    "earth",
    "elle",
    "eth",
    "eys",
    "eyth",
    "felle",
    "fionn",
    "flys",
    "fyll",
    "fynn",
    "fyr",
    "fys",
    "i",
    "ille",
    "ina",
    "ira",
    "isa",
    "ithi",
    "itt",
    "la",
    "lam",
    "lana",
    "larna",
    "lath",
    "leann",
    "leath",
    "lel",
    "lelle",
    "leth",
    "let",
    "lielle",
    "lieth",
    "lyann",
    "nelle",
    "nem",
    "neth",
    "ni",
    "niell",
    "nith",
    "ras",
    "reann",
    "rell",
    "relle",
    "rielle",
    "ris",
    "rith",
    "rys",
    "sar",
    "sath",
    "ser",
    "seth",
    "sir",
    "sith",
    "sor",
    "soth",
    "shar",
    "sher",
    "shir",
    "sys",
    "tar",
    "teal",
    "teann",
    "ter",
    "thea",
    "ther",
    "thi",
    "thryn",
    "thyn",
    "tir",
    "tor",
    "tos",
    "tryan",
    "trys",
    "yll",
    "yrs",
    "ys",
]
# halfling name = name1 + name2M/F
halfling_name1_list = [
    "Bag",
    "Balf",
    "Berc",
    "Bill",
    "Bobb",
    "Bodg",
    "Bog",
    "Bom",
    "Bonn",
    "Brog",
    "Bulc",
    "Bull",
    "Bust",
    "Cam",
    "Cap",
    "Ced",
    "Chund",
    "Clog",
    "Clof",
    "Cob",
    "Cog",
    "Crum",
    "Crump",
    "Curl",
    "Dod",
    "Dog",
    "Dott",
    "Dram",
    "Drub",
    "Drog",
    "Dron",
    "Durc",
    "Elm",
    "Enn",
    "Ermin",
    "Ethan",
    "Falc",
    "Fald",
    "Falm",
    "Far",
    "Fild",
    "Flac",
    "Fogg",
    "Frit",
    "Ful",
    "Func",
    "Gaff",
    "Galb",
    "Gamm",
    "Gert",
    "Giff",
    "Gild",
    "Gon",
    "Grop",
    "Gudd",
    "Gump",
    "Ham",
    "Hal",
    "Hart",
    "Harp",
    "Jac",
    "Jas",
    "Jasp",
    "Joc",
    "Lac",
    "Lil",
    "Lob",
    "Lott",
    "Lud",
    "Lurc",
    "Mad",
    "Mag",
    "Man",
    "May",
    "Mer",
    "Mul",
    "Murc",
    "Murd",
    "Nag",
    "Nell",
    "Nobb",
    "Od",
    "Og",
    "Old",
    "Pipp",
    "Podd",
    "Porc",
    "Riff",
    "Rip",
    "Rob",
    "Sam",
    "Supp",
    "Taff",
    "Talb",
    "Talc",
    "Tay",
    "Tom",
    "Wald",
    "Watt",
    "Will",
]
halfling_male_name2_list = [
    "belly",
    "er",
    "fast",
    "in",
    "it",
    "mutch",
    "o",
    "odoc",
    "riadoc",
    "regar",
    "wick",
    "wise",
    "wit",
    "y",
]
halfling_female_name2_list = [
    "a",
    "adell",
    "alot",
    "apple",
    "bell",
    "berry",
    "eena",
    "ella",
    "era",
    "et",
    "ia",
    "flower",
    "lotta",
    "petal",
    "riella",
    "sweet",
    "trude",
    "rose",
    "willow",
    "y",
]
human_surname_list = [
    "Adelhof",
    "Albrecht",
    "Allenstag",
    "Altmann",
    "Atzwig",
    "Bacher",
    "Baer",
    "Baumann",
    "Becker",
    "Behn",
    "Betz",
    "Beyer",
    "Bischof",
    "Boehm",
    "Breitenbach",
    "Breuer",
    "Dahmbach",
    "Delfholt",
    "Drakenhof",
    "Drauwulf",
    "Durrbein",
    "Ehrhard",
    "Eisenhauer",
    "Eschlimann",
    "Falkenheim",
    "Fehr",
    "Fiegler",
    "Fleischer",
    "Frohlich",
    "Frueh",
    "Fuchs",
    "Gaffwig",
    "Gaertner",
    "Gebauer",
    "Godtgraf",
    "Grunenwald",
    "Guth",
    "Haintz",
    "Herz",
    "Herzog",
    "Hirtzel",
    "Hoch",
    "Hoefer",
    "Hofstetter",
    "Jaeger",
    "Jochutz",
    "Jutzenbach",
    "Kalb",
    "Kaltenbach",
    "Kraemer",
    "Krebs",
    "Kuhn",
    "Kummel",
    "Konig",
    "Konigsamen",
    "Lang",
    "Lankdorf",
    "Liess",
    "Lebengut",
    "Lutzen",
    "Machholt",
    "Meusmann",
    "Meyer",
    "Mohr",
    "Muller",
    "Nachtmann",
    "Naubhof",
    "Netzhoch",
    "Neumann",
    "Niederlitz",
    "Nuhr",
    "Oberholtzer",
    "Ohrsten",
    "Otzlowe",
    "Reichert",
    "Reifsneider",
    "Riese",
    "Rohrig",
    "Reiss",
    "Schaffer",
    "Schaumer",
    "Scherer",
    "Schultz",
    "Schleiermacher",
    "Schreiber",
    "Schwalb",
    "Steiner",
    "Tabbeck",
    "Teuber",
    "Tolzen",
    "Trachsel",
    "Weber",
    "Wechsler",
    "Wirtz",
    "Widmannn",
    "Widmer",
    "Veit",
    "Vogt",
    "Vogel",
    "Zumwald",
]
elf_surname_list = [
    "Białowłosy",
    "Błękit Pióra",
    "Błękit Skrzydła",
    "Błysk Klingi",
    "Błysk Pioruna",
    "Błysk Stali",
    "Bystrooki",
    "Ciemnowłosy",
    "Cienista Dolina",
    "Czarne Drzewo",
    "Czarny Kurhan",
    "Czysty Zdrój",
    "Dech Lasu",
    "Dębowy Konar",
    "Dotyk Nocy",
    "Dzikie Serce",
    "Gwiazda Wieczorna",
    "Gwiazda Zaranna",
    "Gwiezdne Oko",
    "Gwiezdny Ogień",
    "Gwiezdny Pył",
    "Jasna Gwiazda",
    "Jasnooki",
    "Jastrzębie Oko",
    "Jaśniejący",
    "Jeleni Skok",
    "Kieł Wilka",
    "Korona Słońca",
    "Krzyk Puchacza",
    "Księżycowy Blask",
    "Księżycowy Mrok",
    "Kwiat Młodości",
    "Lot Sokoła",
    "Lśniąca Góra",
    "Lśniący Grot",
    "Lśniący Księżyc",
    "Mądre Serce",
    "Mądrość Klanu",
    "Mężne Serce",
    "Młody Liść",
    "Moc Dębu",
    "Moc Korzeni",
    "Moc Różdżki",
    "Morska Fala",
    "Morska Piana",
    "Mroczne Ostrze",
    "Nocny Łowca",
    "Oko Wilka",
    "Oko Wizji",
    "Oko Zieleni",
    "Opadający Liść",
    "Opoka Siły",
    "Orzeł Mroku",
    "Ostre Ostrze",
    "Ostry Grot",
    "Pajęcza Nić",
    "Patrzący W Dal",
    "Podmuch Wichury",
    "Poranna Rosa",
    "Półksiężyc",
    "Promyk Słońca",
    "Przyjaciel Zwierząt",
    "Radosne Serce",
    "Różany Kwiat",
    "Ryk Burzy",
    "Silnoręki",
    "Smoczy Brat",
    "Smukłe Ostrze",
    "Smukły Grot",
    "Spokój Fal",
    "Spokój Kamienia",
    "Spokój Lasu",
    "Srebrnowłosy",
    "Srebrny Liść",
    "Srebrny Świt",
    "Strzała Mocy",
    "Szybki Grot",
    "Szybkie Ostrze",
    "Śnieżny Puch",
    "Śpiew Dzikości",
    "Śpiew Wiatru",
    "Ukryty W Cieniu",
    "Uśmiech Wiatru",
    "Wartki Strumyk",
    "Wędrowiec",
    "Wiatr Wśród Traw",
    "Wiatroskrzydły",
    "Wieża Mądrości",
    "Wodny Wir",
    "Wschodzące Słońce",
    "Wszechwidzący",
    "Wyniosły Dąb",
    "Wysoki Brzeg",
    "Zachodzące Słońce",
    "Zieleń Pióra",
    "Zieleń Skrzydła",
    "Zielona Dolina",
    "Złocisty Obłok",
    "Złota Struga",
    "Złotowłosy",
]
halfling_surname_list = [
    "Altannik",
    "Badylarz",
    "Beczułka",
    "Bielinek",
    "Brzeżek",
    "Brzuchacz",
    "Byliniak",
    "Cichobieg",
    "Cierniak",
    "Długonos",
    "Długouch",
    "Drapak",
    "Drewniak",
    "Dudziarz",
    "Dziwaczek",
    "Figlarz",
    "Futrzak",
    "Glistnik",
    "Głuptak",
    "Groszek",
    "Grzechotek",
    "Grzywacz",
    "Gwizdawek",
    "Iglarz",
    "Jabłecznik",
    "Jagódka",
    "Jaskółka",
    "Kaczeniec",
    "Kasztanek",
    "Kędziorek",
    "Kociak",
    "Kociołek",
    "Kogut",
    "Kolcownik",
    "Koniczynka",
    "Koralik",
    "Kosturek",
    "Kotlarz",
    "Kret",
    "Kręciołek",
    "Kruczek",
    "Krupnik",
    "Kulawik",
    "Kwietniak",
    "Łazik",
    "Łąkołaz",
    "Łodyżek",
    "Marudniak",
    "Mieszek",
    "Młynek",
    "Morwa",
    "Mroczek",
    "Niemysł",
    "Okruszek",
    "Opijus",
    "Otoczak",
    "Owsianniak",
    "Pagórek",
    "Paluch",
    "Piaszczak",
    "Piwniak",
    "Piwosz",
    "Podpłomyk",
    "Popiołek",
    "Przebiśnieg",
    "Radośnik",
    "Robaczek",
    "Rogaś",
    "Ryjek",
    "Rzęsawik",
    "Sknerus",
    "Skoblik",
    "Skórniak",
    "Słomnik",
    "Stoczek",
    "Stopowiąz",
    "Stopowłaz",
    "Sucharek",
    "Szarak",
    "Szarotek",
    "Śnieżynka",
    "Trzęsawiec",
    "Warkoczyk",
    "Wąsacz",
    "Wąwoźnik",
    "Wesołek",
    "Węgielek",
    "Wiatrownik",
    "Wierzbek",
    "Wietrzyk",
    "Wilczomlecz",
    "Wilkowyj",
    "Wodniak",
    "Wstążka",
    "Zagórnik",
    "Zawijas",
    "Zieleniak",
    "Złocisz",
    "Żarnik",
    "Żniwiarz",
]
# town_dict only contain typical birthplaces for human from The Empire
town_dict = {
    "Averland": {
        (1, 25): "Averheim (stolica)",
        (26, 35): "Grenzstadt (miasto)",
        (36, 45): "Hochsleben (miasto)",
        (46, 54): "Loningbruck (miasto)",
        (55, 63): "Wuppertal (miasto)",
        (64, 72): "Agbeiten (wioska)",
        (73, 81): "Braundorf (wioska)",
        (82, 91): "Kotzenheim (wioska)",
        (92, 100): "Zecher (wioska)",
    },
    "Hochland": {
        (1, 25): "Hergig (stolica)",
        (26, 38): "Breder (miasto)",
        (39, 51): "Krudenwald (miasto)",
        (52, 64): "Bergendorf (wioska)",
        (65, 77): "Esk (wioska)",
        (78, 90): "Gruyden (wioska)",
        (91, 100): "Koerin (wioska)",
    },
    "Middenland": {
        (1, 25): "Middenheim (stolica)",
        (26, 37): "Delberz (miasto)",
        (38, 49): "Grimminhagen (miasto)",
        (50, 60): "Norderingen (miasto)",
        (61, 70): "Holzbeck (wioska)",
        (71, 80): "Immelscheld (wioska)",
        (81, 90): "Pritzstock (wioska)",
        (91, 100): "Sokh (wioska)",
    },
    "Nordland": {
        (1, 25): "Salzenmund (stolica)",
        (26, 38): "Beeckerhoven (miasto)",
        (39, 51): "Dietershafen (miasto)",
        (52, 64): "Grafenrich (wioska)",
        (65, 77): "Luftberg (wioska)",
        (78, 90): "Oldenlitz (wioska)",
        (91, 100): "Wilhelmskoog (wioska)",
    },
    "Ostermark": {
        (1, 25): "Bechafen (stolica)",
        (26, 38): "Eisental (miasto)",
        (39, 51): "Remer (miasto)",
        (52, 64): "Bissendorf (wioska)",
        (65, 77): "Dorna (wioska)",
        (78, 90): "Fortenhaf (wioska)",
        (91, 100): "Heffengen (wioska)",
    },
    "Ostland": {
        (1, 25): "Wolfenburg (stolica)",
        (26, 38): "Ferlangen (miasto)",
        (39, 51): "Vandengart (miasto)",
        (52, 64): "Boven (wioska)",
        (65, 77): "Lubrecht (wioska)",
        (78, 90): "Smallhof (wioska)",
        (91, 100): "Zundap (wioska)",
    },
    "Reikland": {
        (1, 25): "Altdorf (stolica Imperium)",
        (26, 40): "Nuln (duże miasto)",
        (41, 50): "Bogenhafen (miasto)",
        (51, 60): "Grunburg (miasto)",
        (61, 70): "Halheim (wioska)",
        (71, 80): "Misthausen (wioska)",
        (81, 90): "Teufelfeuer (wioska)",
        (91, 100): "Weissbruck (wioska)",
    },
    "Stirland": {
        (1, 25): "Wurtbad (stolica)",
        (26, 38): "Drakenhof (miasto)",
        (39, 51): "Waldenhof (miasto)",
        (52, 64): "Eschedorf (wioska)",
        (65, 77): "Furtzhausen (wioska)",
        (78, 90): "Schwartzhafen",
        (91, 100): "Wurstheim",
    },
    "Talabekland": {
        (1, 25): "Talabheim (stolica)",
        (26, 38): "Bek (miasto)",
        (39, 51): "Kemperbad (miasto)",
        (52, 64): "Garndorf (wioska)",
        (65, 77): "Rangenhof (wioska)",
        (78, 90): "Wellenborn (wioska)",
        (91, 100): "Zurin (wioska)",
    },
    "Wissenland": {
        (1, 25): "Wissenburg (stolica)",
        (26, 38): "Grissenwald (miasto)",
        (39, 51): "Pfeildorf (miasto)",
        (52, 64): "Ambosstein (wioska)",
        (65, 77): "Konigsdorf (wioska)",
        (78, 90): "Segeldorf (wioska)",
        (91, 100): "Steingart (wioska)",
    },
}
dwarf_birthplace_list = [
    "Karak Norn (Góry Szare)",
    "Karak Izor (Przeskok)",
    "Karak Hirn (Góry Czarne)",
    "Karak Kadrin (Góry Krańca Świata)",
    "Karaz-a-Karak (Góry Krańca Świata)",
    "Zhufbar (Góry Krańca Świata)",
    "Bark Varr (Czarna Zatoka)",
]
elf_birthplace_dict = {
    (1, 20): "Altdorf",
    (21, 40): "Marienburg",
    (41, 70): "Las Laurelorn",
    (71, 85): "Wielki Las",
    (86, 100): "Las Reikwald",
}
any_skills = {
    "wiedza (dowolna)": [
        "wiedza (Imperium)",
        "wiedza (Bretonia)",
        "wiedza (Estalia)",
        "wiedza (Jałowa Kraina)",
        "wiedza (Kislev)",
        "wiedza (Księstwa Graniczne)",
        "wiedza (Norska)",
        "wiedza (Tilea)",
        "wiedza (elfy)",
        "wiedza (niziołki)",
        "wiedza (krasnoludy)",
        "wiedza (ogry)",
    ],
    "kuglarstwo (dowolne)": [
        "kuglarstwo (akrobatyka)",
        "kuglarstwo (aktorstwo)",
        "kuglarstwo (błaznowanie)",
        "kuglarstwo (gawędziarstwo)",
        "kuglarstwo (komedianctwo)",
        "kuglarstwo (mimika)",
        "kuglarstwo (muzykalność)",
        "kuglarstwo (połykanie ognia)",
        "kuglarstwo (śpiew)",
        "kuglarstwo (taniec)",
        "kuglarstwo (wróżenie z dłoni)",
        "kuglarstwo (żonglerka)",
    ],
    "nauka (dowolna)": [
        "nauka (alchemia)",
        "nauka (astronomia)",
        "nauka (demonologia)",
        "nauka (filozofia)",
        "nauka (genealogia/heraldyka)",
        "nauka (historia)",
        "nauka (inżynieria)",
        "nauka (magia)",
        "nauka (matematyka)",
        "nauka (nekromancja)",
        "nauka (prawo)",
        "nauka (runy)",
        "nauka (strategia/taktyka)",
        "nauka (sztuka)",
        "nauka (teologia)",
    ],
    "rzemiosło (dowolne)": [
        "rzemiosło (aptekarstwo)",
        "rzemiosło (bednarstwo)",
        "rzemiosło (garbarstwo)",
        "rzemiosło (gotowanie)",
        "rzemiosło (górnictwo)",
        "rzemiosło (handel)",
        "rzemiosło (jubilerstwo)",
        "rzemiosło (kaligrafia)",
        "rzemiosło (kamieniarstwo)",
        "rzemiosło (kartografia)",
        "rzemiosło (kowalstwo)",
        "rzemiosło (krawiectwo)",
        "rzemiosło (młynarstwo)",
        "rzemiosło (piwowarstwo)",
        "rzemiosło (płatnerstwo)",
        "rzemiosło (rusznikarstwo)",
        "rzemiosło (rymarstwo)",
        "rzemiosło (stolarstwo)",
        "rzemiosło (szkutnictwo)",
        "rzemiosło (szewstwo)",
        "rzemiosło (sztuka)",
        "rzemiosło (świecarstwo)",
        "rzemiosło (uprawa ziemi)",
        "rzemiosło (wyrób łuków)",
        "rzemiosło (zielarstwo)",
        "rzemiosło (złotnictwo)",
    ],
    "znajomość języka (dowolny)": [
        "znajomość języka (bretoński)",
        "znajomość języka (eltharin)",
        "znajomość języka (estalijski)",
        "znajomość języka (khazalid)",
        "znajomość języka (kislevski)",
        "znajomość języka (norski)",
        "znajomość języka (tileański)",
        "znajomość języka (staroświatowy)",
        "znajomość języka (niziołków)",
        "znajomość języka (klasyczny)",
        "znajomość języka (gobliński)",
        "znajomość języka (grumbarth)",
        "znajomość języka (mroczna mowa)",
    ],
    "sekretne znaki (dowolne)": [
        "sekretne znaki (łowców)",
        "sekretne znaki (rycerzy zakonnych)",
        "sekretne znaki (złodziei)",
        "sekretne znaki (zwiadowców)",
        "sekretne znaki (gildii)",
    ],
    "sekretny język (dowolny)": [
        "sekretny język (bitweny)",
        "sekretny język (łowców)",
        "sekretny język (złodziei)",
        "sekretny język (gildii)",
    ],
}
any_ability = {
    "runa (dowolna<10)": [
        "runa szybkości",
        "runa ciosu",
        "runa ochrony",
        "runa kamienia",
    ],
    "runa (dowolna<10)2": [
        "runa szybkości",
        "runa ciosu",
        "runa ochrony",
        "runa kamienia",
    ],  # handle 2nd same ability expection rune dwarf
    "broń specjalna (dowolna)": [
        "broń specjalna (dwuręczna)",
        "broń specjalna (kawaleryjska)",
        "broń specjalna (mechaniczna)",
        "broń specjalna (palna)",
        "broń specjalna (parująca)",
        "broń specjalna (rzucana)",
        "broń specjalna (szermiercza)",
        "broń specjalna (unieruchamiająca)",
        "broń specjalna (korbacze)",
        "broń specjalna (kusze)",
        "broń specjalna (długi łuk)",
        "broń specjalna (proca)",
    ],
    "magia powszechna (dowolna)": [
        "magia powszechna (dotyk na odległość)",
        "magia powszechna (magicnzy alarm)",
        "magia powszechna (magiczna broń)",
        "magia powszechna (magiczny zamek)",
        "magia powszechna (pancerz Eteru)",
        "magia powszechna (podniebny chód)",
        "magia powszechna (rozproszenie magii)",
        "magia powszechna (uciszenie)",
    ],
}

# here order matters
basic_skills = [
    "charakteryzacja",
    "dowodzenie",
    "hazard",
    "jeździectwo",
    "mocna głowa",
    "opieka nad zwierzętami",
    "plotkowanie",
    "pływanie",
    "powożenie",
    "przekonywanie",
    "przeszukiwanie",
    "skradanie się",
    "spostrzegawczość",
    "sztuka przetrwania",
    "targowanie",
    "ukrywanie się",
    "wioślarstwo",
    "wspinaczka",
    "wycena",
    "zastraszanie"
]

starting_human_skills = [
    "plotkowanie",
    "wiedza (Imperium)",
    "znajomość języka (staroświatowy)",
    ]

starting_halfling_skills = [
    "plotkowanie",
    "wiedza (niziołki)",
    "znajomość języka (staroświatowy)",
    "znajomość języka (niziołków)",
    "nauka (genealogia/heraldyka)",
]

starting_halfling_skills_optional = [
    "rzemiosło (gotowanie)", 
    "rzemiosło (uprawa ziemi)"
    ]

starting_halfling_abilities = [
    "broń specjalna (proca)",
    "odporność na Chaos",
    "widzenie w ciemności",
]

starting_dwarf_skills = [
    "wiedza (krasnoludy)",
    "znajomość języka (khazalid)",
    "znajomość języka (staroświatowy)",
]

starting_dwarf_skills_optional = [
    "rzemiosło (górnictwo)",
    "rzemiosło (kamieniarstwo)",
    "rzemiosło (kowalstwo)",
]

starting_dwarf_abilities = [
    "krasnoludzki fach",
    "krzepki",
    "odporność na magię",
    "odwaga",
    "widzenie w ciemności",
    "zapiekła nienawiść",
]

starting_elf_skills = [
    "wiedza (elfy)",
    "znajomość języka (eltharin)",
    "znajomość języka (staroświatowy)",
]

starting_elf_ablities = [
    "bystry wzrok",
    "widzenie w ciemności",
]

starting_elf_ablities_optional1 = ["broń specjalna (długi łuk)", "zmysł magii"]

starting_elf_ablities_optional2 = ["opanowanie", "błyskotliwość"]

halfling_most_common_birthplace = "Kraina Zgromadzenia"