human_profession_mapping = {
    (1,16): 'Akolita',
    (17,28): 'Aptekarz',
    (29,32): 'Bagiennik',
    (33,44): 'Bajarz',
    (45,48): 'Balsamista',
    (49,64): 'Banita',
    (65,68): 'Berserker z Norski',
    (69,80): 'Błędny rycerz',
    (81,88): 'Były więzień',
    (89,92): 'Cenobita',
    (93,104): 'Chłop',
    (105,112): 'Ciura obozowa',
    (113,128): 'Cyrkowiec',
    (129,140): 'Cyrulik',
    (141,144): 'Czekista',
    (145,148): 'Doker',
    (149,160): 'Dyletant',
    (161,164): 'Fanatyk',
    (165,180): 'Flisak',
    (181,184): 'Gazeciarz',
    (185,192): 'Giermek',
    (193,204): 'Gladiator',
    (205,212): 'Górnik',
    (213,220): 'Grabarz',
    (221,224): 'Grabieżca',
    (225,236): 'Guślarz',
    (237,244): 'Handlarz końmi',
    (245,256): 'Hiena cmentarna',
    (257,260): 'Kadet',
    (261,276): 'Kanciarz',
    (277,284): 'Kartograf',
    (285,288): 'Koczownik',
    (289,300): 'Kominiarz',
    (301,304): 'Korsarz',
    (305,312): 'Kozak kislevski',
    (313,320): 'Latarnik',
    (321,332): 'Leśnik',
    (333,344): 'Łowca',
    (345,356): 'Łowca nagród',
    (357,368): 'Mieszczanin',
    (369,372): 'Mytnik',
    (373,388): 'Najemnik',
    (389,392): 'Niewolnik',
    (393,404): 'Ochotnik',
    (405,420): 'Ochroniarz',
    (421,432): 'Oprych',
    (433,444): 'Pachołek',
    (445,448): 'Pasterz z Carcasonne',
    (449,456): 'Paź',
    (457,468): 'Pielgrzym',
    (469,476): 'Pielgrzym Graala',
    (477,480): 'Pirat rzeczny',
    (481,492): 'Podżegacz',
    (493,500): 'Poganiacz bydła',
    (501,508): 'Poganiacz mułów',
    (509,516): 'Pogranicznik',
    (517,520): 'Pokutnik',
    (521,528): 'Porywacz zwłok',
    (529,536): 'Poskramiacz niedźwiedzi',
    (537,544): 'Posłaniec',
    (545,548): 'Prawnik',
    (549,556): 'Przemytnik',
    (557,564): 'Przepatrywacz',
    (565,572): 'Przewoźnik',
    (573,576): 'Pustelnik',
    (577,580): 'Rogaty łowca',
    (581,592): 'Rolnik',
    (593,596): 'Rozjemca',
    (597,608): 'Rybak',
    (609,624): 'Rzemieślnik',
    (625,636): 'Rzezimieszek',
    (637,640): 'Skald',
    (641,652): 'Skarbnik',
    (653,664): 'Skryba',
    (665,672): 'Sługa',
    (673,684): 'Strażnik',
    (685,700): 'Strażnik dróg',
    (701,708): 'Strażnik kanałów',
    (709,716): 'Strażnik rzeczny',
    (717,720): 'Strażnik świątynny',
    (721,724): 'Strażnik tuneli',
    (725,732): 'Strażnik więzienny',
    (733,736): 'Streltsi',
    (737,740): 'Strzygański mistyk',
    (741,760): 'Szczurołap',
    (761,772): 'Szeptucha',
    (773,776): 'Szermierz estalijski',
    (777,792): 'Szlachcic',
    (793,796): 'Szperacz',
    (797,808): 'Szuler',
    (809,816): 'Śmieciarz',
    (817,824): 'Uczennica lodowej wiedźmy',
    (825,840): 'Uczeń czarodzieja',
    (841,848): 'Uczeń guślarza',
    (849,856): 'Węglarz',
    (857,864): 'Wielorybnik',
    (865,872): 'Włóczykij',
    (873,876): 'Woj',
    (877,888): 'Woźnica',
    (889,896): 'Wróżbita',
    (897,904): 'Zakapturzony',
    (905,916): 'Zarządca',
    (917,924): 'Zbieracz łajna',
    (925,940): 'Złodziej',
    (941,948): 'Żabiarka',
    (949,960): 'Żak',
    (961,972): 'Żeglarz',
    (973,984): 'Żołnierz',
    (985,1000): 'Żołnierz okrętowy'
}
halfling_profession_mapping = {
    (1,13): 'Akolita',
    (14,26): 'Aptekarz',
    (27,55): 'Bajarz',
    (56,62): 'Balsamista',
    (63,82): 'Banita',
    (83,89): 'Były więzień',
    (90,114): 'Chłop',
    (115,127): 'Ciura obozowa',
    (128,147): 'Cyrkowiec',
    (148,154): 'Cyrulik',
    (155,174): 'Dyletant',
    (175,194): 'Gazeciarz',
    (195,201): 'Grabarz',
    (202,225): 'Hiena cmentarna',
    (226,258): 'Kanciarz',
    (259,271): 'Kartograf',
    (272,304): 'Kominiarz',
    (305,317): 'Latarnik',
    (318,350): 'Łowca',
    (351,363): 'Łowca nagród',
    (364,376): 'Mieszczanin',
    (377,389): 'Mytnik',
    (390,414): 'Najemnik',
    (415,421): 'Niewolnik',
    (422,446): 'Ochotnik',
    (447,449): 'Oprych',
    (450,469): 'Paź',
    (470,482): 'Pielgrzym',
    (483,502): 'Podżegacz',
    (503,509): 'Poganiacz mułów',
    (510,516): 'Pogranicznik',
    (517,546): 'Porywacz zwłok',
    (547,579): 'Posłaniec',
    (580,592): 'Prawnik',
    (593,612): 'Przemytnik',
    (613,619): 'Przewoźnik',
    (620,632): 'Rolnik',
    (633,645): 'Rybak',
    (646,687): 'Rzemieślnik',
    (688,694): 'Skarbnik',
    (695,707): 'Skryba',
    (708,745): 'Sługa',
    (746,769): 'Strażnik',
    (770,782): 'Strażnik kanałów',
    (783,815): 'Stażnik pól',
    (816,828): 'Strażnik świątynny',
    (829,838): 'Szczurołap',
    (839,851): 'Szlachcic',
    (852,864): 'Szuler',
    (865,871): 'Śmieciarz',
    (872,891): 'Węglarz',
    (892,916): 'Włóczykij',
    (917,929): 'Zarządca',
    (930,936): 'Zbieracz łajna',
    (937,974): 'Złodziej',
    (975,987): 'Żak',
    (988,1000): 'Żołnierz'
}
dwarf_profession_mapping = {
    (1,15): 'Akolita',
    (16,30): 'Bajarz',
    (31,51): 'Banita',
    (52,66): 'Były więzień',
    (67,87): 'Cyrkowiec',
    (88,129): 'Czeladnik run',
    (130,144): 'Doker',
    (145,159): 'Dyletant',
    (160,194): 'Gladiator',
    (195,229): 'Goniec',
    (230,271): 'Górnik',
    (272,292): 'Hiena cmentarna',
    (293,320): 'Kanciarz',
    (321,335): 'Kartograf',
    (336,363): 'Łowca',
    (364,378): 'Łowca nagród',
    (379,399): 'Mieszczanin',
    (400,414): 'Mytnik',
    (415,456): 'Najemnik',
    (457,464): 'Niewolnik',
    (465,492): 'Ochotnik',
    (493,520): 'Ochroniarz',
    (521,535): 'Oprych',
    (536,550): 'Pielgrzym',
    (551,565): 'Podżegacz',
    (566,586): 'Poganiacz mułów',
    (587,607): 'Przemytnik',
    (608,635): 'Rzemieślnik',
    (636,663): 'Rzezimieszek',
    (664,678): 'Skryba',
    (679,693): 'Sługa',
    (694,713): 'Strażnik',
    (714,728): 'Strażnik kanałów',
    (729,743): 'Strażnik świątynny',
    (744,771): 'Strażnik więzienny',
    (772,799): 'Szczurołap',
    (800,814): 'Szlachcic',
    (815,829): 'Szuler',
    (830,857): 'Tarczownik',
    (858,885): 'Włóczykij',
    (886,900): 'Woźnica',
    (901,928): 'Zabójca trolli',
    (929,949): 'Złodziej',
    (950,964): 'Żak',
    (965,972): 'Żeglarz',
    (973,1000): 'Żołnierz'
}
elf_profession_mapping = {
    (1,7): 'Aptekarz',
    (8,64): 'Uczeń czarodzieja',
    (65,78): 'Ochroniarz',
    (79,99): 'Łowca nagród',
    (100,113): 'Kartograf',
    (114,141): 'Dyletant',
    (142,176): 'Cyrkowiec',
    (177,218): 'Rzecznik rodu',
    (219,222): 'Szuler',
    (223,278): 'Łowca',
    (279,292): 'Akolita',
    (293,342): 'Wojownik klanowy',
    (343,377): 'Żołnierz okrętowy',
    (378,412): 'Najemnik',
    (413,450): 'Posłaniec',
    (451,464): 'Szlachcic',
    (465,494): 'Banita',
    (495,534): 'Przepatrywacz',
    (535,548): 'Pielgrzym',
    (549,562): 'Gladiator',
    (563,600): 'Bajarz',
    (601,625): 'Strażnik rzeczny',
    (626,665): 'Kanciarz',
    (666,705): 'Skryba',
    (706,745): 'Żeglarz',
    (746,752): 'Niewolnik',
    (753,780): 'Przemytnik',
    (781,815): 'Żak',
    (816,856): 'Złodziej',
    (857,869): 'Oprych',
    (870,919): 'Rzemieślnik',
    (920,961): 'Włóczykij',
    (962,1000): 'Leśnik'
}
halfling_ability_mapping = {
    (1,4): 'Bardzo silny',
    (5,9): 'Bardzo szybki',
    (10,13): 'Błyskotliwość',
    (14,18): 'Bystry wzrok',
    (19,23): 'Charyzmatyczny',
    (24,28): 'Czuły słuch',
    (29,34): 'Geniusz arytmetyczny',
    (35,39): 'Krzepki',
    (40,44): 'Naśladowca',
    (45,49): 'Niezwykle odporny',
    (50,53): 'Oburęczność',
    (54,58): 'Odporność na choroby',
    (59,62): 'Odporność na magię',
    (63,64): 'Odporność na trucizny',
    (65,68): 'Odporność psychiczna',
    (69,73): 'Opanowanie',
    (74,78): 'Strzelec wyborowy',
    (79,82): 'Szczęście',
    (83,87): 'Szósty zmysł',
    (88,92): 'Szybki refleks',
    (93,96): 'Twardziel',
    (97,100): 'Urodzony wojownik'
}
human_ability_mapping = {
    (1,4): 'Bardzo silny',
    (5,9): 'Bardzo szybki',
    (10,13): 'Błyskotliwość',
    (14,18): 'Bystry wzrok',
    (19,22): 'Charyzmatyczny',
    (23,27): 'Czuły słuch',
    (28,31): 'Geniusz arytmetyczny',
    (32,35): 'Krzepki',
    (36,40): 'Naśladowca',
    (41,44): 'Niezwykle odporny',
    (45,49): 'Oburęczność',
    (50,53): 'Odporność na choroby',
    (54,57): 'Odporność na magię',
    (58,61): 'Odporność na trucizny',
    (62,66): 'Odporność psychiczna',
    (67,71): 'Opanowanie',
    (72,75): 'Strzelec wyborowy',
    (76,79): 'Szczęście',
    (80,83): 'Szósty zmysł',
    (84,87): 'Szybki refleks',
    (88,91): 'Twardziel',
    (92,95): 'Urodzony wojownik',
    (96,100): 'Widzenie w ciemności'
}
ability_modify_attr = {
    'Urodzony wojownik': 'WW',
    'Strzelec wyborowy': 'US',
    'Bardzo silny': 'K',
    'Niezywkle odporny': 'Odp',
    'Szybki refleks': 'Zr',
    'Błyskotliwość': 'Int',
    'Opanowanie': 'SW',
    'Charyzmatyczny': 'Ogd',
    'Twardziel': 'Żyw',
    'Bardzo szybki': 'Sz',
}
# dwarf weight as common
common_weight_mapping = { 
    (1,1): 45,
    (2,10): 50,
    (11,20): 55,
    (21,30): 60,
    (31,40): 65,
    (41,50): 70,
    (51,60): 75,
    (61,70): 80,
    (71,80): 85,
    (81,90): 90,
    (91,99): 95,
    (100,100): 100
}
halfling_weight_mapping = { 
    (1,1): 35,
    (2,10): 35,
    (11,20): 40,
    (21,30): 40,
    (31,40): 45,
    (41,50): 45,
    (51,60): 50,
    (61,70): 50,
    (71,80): 55,
    (81,90): 60,
    (91,99): 65,
    (100,100): 70
}
human_hair_list = [
  'Popielaty',
  'Ciemny blond',
  'Blond',
  'Rudy',
  'Ciemny rudy',
  'Jasnobrązowy',
  'Brązowy',
  'Brązowy',
  'Ciemnobrązowy',
  'Czarny'
]
halfling_hair_list = [
  'Popielaty',
  'Ciemny blond',
  'Blond',
  'Blond',
  'Rudy',
  'Ciemny rudy',
  'Jasnobrązowy',
  'Brązowy',
  'Ciemnobrązowy',
  'Czarny'
]
dwarf_hair_list = [
  'Popielaty',
  'Blond',
  'Ciemny rudy',
  'Czerowny',
  'Rudy',
  'Brązowy',
  'Brązowy',
  'Ciemnobrązowy',
  'Czarny',
  'Kruczoczarny'
]
elf_hair_list = [
  'Srebrny',
  'Biały',
  'Jasny blond',
  'Ciemny blond',
  'Miedziany',
  'Jasnobrązowy',
  'Kasztanowy',
  'Brązowy',
  'Ciemnobrązowy',
  'Czarny'
]
human_eye_list = [
  'Szary',
  'Ciemnoniebieski',
  'Niebieski',
  'Zielony',
  'Piwny',
  'Jasnobrązowy',
  'Brązowy',
  'Ciemnobrązowy',
  'Fioletowy',
  'Czarny'
]
halfling_eye_list = [
  'Niebieski',
  'Orzechowy',
  'Orzechowy',
  'Jasnobrązowy',
  'Jasnobrązowy',
  'Brązowy',
  'Brązowy',
  'Ciemnobrązowy',
  'Ciemnobrązowy',
  'Ciemnobrązowy'
]
dwarf_eye_list = [
  'Szary',
  'Ciemnoniebieski',
  'Piwny',
  'Jasnobrązowy',
  'Jasnobrązowy',
  'Brązowy',
  'Brązowy',
  'Ciemnobrązowy',
  'Ciemnobrązowy',
  'Fioletowy'
]
elf_eye_list = [
  'Szaroniebieski',
  'Niebieski',
  'Zielony',
  'Orzechowy',
  'Kasztanowy',
  'Brązowy',
  'Ciemnobrązowy',
  'Srebrny',
  'Fioletowy',
  'Czarny'
]
special_mapping = {
  (1,5): 'Bielmo na oku',
  (6,10): 'Blizna',
  (11,15): 'Brak brwi',
  (16,20): 'Brak palca',
  (21,25): 'Brak zęba',
  (26,29): 'Brodawki',
  (30,35): 'Blada cera',
  (36,39): 'Duży nos',
  (40,45): 'Duży pieprzyk',
  (46,50): 'Dziwny zapach ciała',
  (51,55): 'Kolczyk w nosie',
  (56,60): 'Kolczyk w uchu',
  (61,65): 'Niewielka łysina',
  (66,70): 'Oczy różnego koloru',
  (71,75): 'Piegi',
  (76,80): 'Poszarpane ucho',
  (81,84): 'Ślady po ospie',
  (85,89): 'Tatuaż',
  (90,94): 'Wystające zęby',
  (95,98): 'Wytrzeszczone oczy',
  (99,100): 'Złamany nos',
}
# halfling siblings = human siblings + 1
siblings_human_mapping = {
  (1,1): 0,
  (2,3): 1,
  (4,5): 2,
  (6,7): 3,
  (8,9): 4,
  (10,10): 5
}
siblings_dwarf_mapping = {
  (1,3): 0,
  (4,7): 1,
  (8,9): 2,
  (10,10): 3
}
siblings_elf_mapping = {
  (1,1): 0,
  (2,5): 1,
  (6,9): 2,
  (10,10): 3
}
star_mapping = {
  (1,5): 'Bębniarz',
  (6,10): 'Dudy',
  (11,15): 'Dwa Byki',
  (16,25): 'Głupiec Mummit',
  (26,30): 'Gwiazda Uroku',
  (31,35): 'Gwiazda Wieczorna',
  (36,40): 'Kocioł Rhyi',
  (41,45): 'Lancet',
  (46,50): 'Mędrzec Mammit',
  (51,55): 'Pas Grungniego',
  (56,60): 'Rozbity Wóz',
  (61,65): 'Smok Dragomas',
  (66,70): 'Sznur Limnera',
  (71,75): 'Tancerka',
  (76,80): 'Tłusty Kozioł',
  (81,85): 'Vobist Ulotny',
  (86,90): 'Wielki Krzyż',
  (91,95): 'Wół Gnuthus',
  (96,98): 'Wymund Pustelnik',
  (99,100): 'Złoty Kogut'
}
# human names lists only contain imperial names
human_female_name_list = [
  'Abbie',
  'Abighild',
  'Abigund',
  'Abigunda',
  'Ada',
  'Ada',
  'Adel',
  'Adelind',
  'Adeline',
  'Adelyn',
  'Adelle',
  'Agathe',
  'Agnete',
  'Aldreda',
  'Alfreda',
  'Alicia',
  'Allane',
  'Althea',
  'Amalie',
  'Amalinde',
  'Amalyn',
  'Anhilda',
  'Annabella',
  'Anna',
  'Anthea',
  'Arabella',
  'Aver',
  'Bechilda',
  'Bella',
  'Bella',
  'Bellane',
  'Benedicta',
  'Berlinda',
  'Berlyn',
  'Bertha',
  'Berthilda',
  'Bess',
  'Bess',
  'Beth',
  'Broncea',
  'Brunhilda',
  'Camilla',
  'Carla',
  'Carlinda',
  'Carlotta',
  'Cilicia',
  'Cilie',
  'Clora',
  'Clothilda',
  'Connie',
  'Constance',
  'Constanza',
  'Cordelia',
  'Dema',
  'Demona',
  'Desdemona',
  'Dorthilda',
  'Drachena',
  'Drachilda',
  'Edhilda',
  'Edith',
  'Edyth',
  'Edythe',
  'Eleanor',
  'Eleanor',
  'Elinor',
  'Elisinda',
  'Elsina',
  'Ella',
  'Ellene',
  'Ellinde',
  'Eloise',
  'Elsa',
  'Elsa',
  'Elsbeth',
  'Elspeth',
  'Elyn',
  'Emagunda',
  'Emelia',
  'Emme',
  'Emmalyn',
  'Emmanuel',
  'Emerlinde',
  'Emerlyn',
  'Erica',
  'Ermina',
  'Erminlind',
  'Esmeralda',
  'Estelle',
  'Etheldreda',
  'Ethelind',
  'Ethelreda',
  'Fay',
  'Frieda',
  'Frieda',
  'Friedhilda',
  'Friedrun',
  'Friedrica',
  'Gabby',
  'Gabby',
  'Gabriele',
  'Galina',
  'Gena',
  'Genevieve',
  'Genoveva',
  'Gerberga',
  'Gerda',
  'Gerlinde',
  'Gertie',
  'Gertrud',
  'Greta',
  'Greta',
  'Gretchen',
  'Grizelda',
  'Grunhilda',
  'Gudrun',
  'Gudryn',
  'Hanna',
  'Hedwig',
  'Heidi',
  'Heidrun',
  'Helga',
  'Herlinde',
  'Herwig',
  'Hilda',
  'Hilda',
  'Hildegart',
  'Hildegund',
  'Honoria',
  'Ida',
  'Ingrid',
  'Ingrun',
  'Ingrund',
  'Irmella',
  'Irmine',
  'Isabella',
  'Isadora',
  'Isolde',
  'Isolde',
  'Jocelin',
  'Johanna',
  'Josie',
  'Karin',
  'Katarine',
  'Katheryn',
  'Katharina',
  'Katerine',
  'Katerine',
  'Keterlind',
  'Keterlyn',
  'Kitty',
  'Kristen',
  'Kristena',
  'Kristyn',
  'Kirsten',
  'Kirsten',
  'Kirstyn',
  'Lavina',
  'Lavinia',
  'Leanor',
  'Leanora',
  'Leticia',
  'Letty',
  'Lena',
  'Lenora',
  'Lisa',
  'Lisbeth',
  'Lizzie',
  'Lorinda',
  'Lorna',
  'Lucinda',
  'Lucretia',
  'Lucie',
  'Ludmilla',
  'Mabel',
  'Madge',
  'Magdalyn',
  'Maggie',
  'Maghilda',
  'Maglind',
  'Maglyn',
  'Magunda',
  'Magreta',
  'Maida',
  'Marien',
  'Marietta',
  'Margaret',
  'Marget',
  'Margreta',
  'Marline',
  'Marlyn',
  'Mathilda',
  'Maude',
  'May',
  'Meg',
  'Melicent',
  'Miranda',
  'Moll',
  'Nathilda',
  'Nellie',
  'Nellie',
  'Nora',
  'Nora',
  'Olga',
  'Olga',
  'Ophelia',
  'Ophelia',
  'Osterhild',
  'Osterhild',
  'Ostelle',
  'Ostelle',
  'Ostia',
  'Ostia',
  'Ottagunda',
  'Ottagunda',
  'Ottaline',
  'Ottaline',
  'Ottilda',
  'Ottilda',
  'Ottilyn',
  'Ottilyn',
  'Perdita',
  'Perdita',
  'Pergale',
  'Pergale',
  'Pergunda',
  'Pergunda',
  'Petronella',
  'Petronella',
  'Philomelia',
  'Philomelia',
  'Reikhilda',
  'Reikhilda',
  'Renata',
  'Renata',
  'Rosabel',
  'Rosabel',
  'Rosabella',
  'Rosabella',
  'Rosale',
  'Rosale',
  'Rosalia',
  'Rosalia',
  'Rosalin',
  'Rosalin',
  'Rosalinde',
  'Rosalinde',
  'Rosamunde',
  'Rosamunde',
  'Rosanne',
  'Rosanne',
  'Rose',
  'Rose',
  'Roz',
  'Roz',
  'Rozhilda',
  'Rozhilda',
  'Salina',
  'Salina',
  'Saltza',
  'Saltza',
  'Sigismunda',
  'Sigrid',
  'Sigrid',
  'Sigunda',
  'Sigunda',
  'Solla',
  'Solla',
  'Styrine',
  'Styrine',
  'Talima',
  'Talima',
  'Theodora',
  'Theodora',
  'Therese',
  'Therese',
  'Tilea',
  'Tilea',
  'Ursula',
  'Ursula',
  'Ulrica',
  'Ulrica',
  'Valeria',
  'Valeria',
  'Verena',
  'Verena',
  'Wilfrieda',
  'Wilfrieda',
  'Wilhelmina',
  'Wilhelmina',
  'Winifred',
  'Winifred',
  'Wolfhilde',
  'Wolfhilde',
  'Zemelda',
  'Zemelda',
  'Zena'
]
human_male_name_list = [
  'Abelhard',
  'Abelhelm',
  'Admund',
  'Adred',
  'Adric',
  'Agis',
  'Alaric',
  'Alberic',
  'Albrecht',
  'Aldebrand',
  'Aldred',
  'Aldric',
  'Alfreid',
  'Altmar',
  'Alric',
  'Andre',
  'Andred',
  'Andric',
  'Anshelm',
  'Anton',
  'Arne',
  'Arnulf',
  'Axel',
  'Axelbrand',
  'Baldred',
  'Baldric',
  'Baldwin',
  'Balthasar',
  'Barnabas',
  'Bart',
  'Bartolf',
  'Bartomar',
  'Bernolt',
  'Bertold',
  'Bertolf',
  'Boris',
  'Bruno',
  'Burgolf',
  'Calvin',
  'Casimir',
  'Caspar',
  'Cedred',
  'Conrad',
  'Corvin',
  'Dagmar',
  'Dankmar',
  'Dankred',
  'Dekmar',
  'Detlef',
  'Diebold',
  'Diel',
  'Dietfried',
  'Dieter',
  'Dietmar',
  'Dietmund',
  'Dietrich',
  'Dirk',
  'Donat',
  'Durnhelm',
  'Eber',
  'Eckel',
  'Eckhart',
  'Edgar',
  'Edmund',
  'Edwin',
  'Ehrhart',
  'Ehrl',
  'Ehrwig',
  'Eldred',
  'Elmeric',
  'Emil',
  'Engel',
  'Engelbert',
  'Engelbrecht',
  'Engelhart',
  'Eodred',
  'Eomund',
  'Erdman',
  'Erdred',
  'Erkenbrand',
  'Erasmus',
  'Erich',
  'Erman',
  'Ernst',
  'Erwin',
  'Eugen',
  'Eustasius',
  'Ewald',
  'Fabian',
  'Faustus',
  'Felix',
  'Ferdinand',
  'Fleugweiner',
  'Fosten',
  'Franz',
  'Frediger',
  'Frederic',
  'Friebald',
  'Friedrich',
  'Gawin',
  'Gerber',
  'Gerhart',
  'Gerlach',
  'Gernar',
  'Gerolf',
  'Gilbrecht',
  'Gisbert',
  'Giselbrecht',
  'Gismar',
  'Goran',
  'Gosbert',
  'Goswin',
  'Gotfried',
  'Gothard',
  'Gottolf',
  'Gotwin',
  'Gregor',
  'Greimold',
  'Grimwold',
  'Griswold',
  'Guido',
  'Gundolf',
  'Gundred',
  'Gunnar',
  'Gunter',
  'Gunther',
  'Gustaf',
  'Hadred',
  'Hadwin',
  'Hagar',
  'Hagen',
  'Haldred',
  'Halman',
  'Hamlyn',
  'Hans',
  'Harbrand',
  'Harman',
  'Hartmann',
  'Haug',
  'Heidric',
  'Heimar',
  'Heinfried',
  'Heinman',
  'Heinrich',
  'Heinz',
  'Helmut',
  'Henlyn',
  'Hermann',
  'Herwin',
  'Hieronymus',
  'Hildebart',
  'Hildebrand',
  'Hildemar',
  'Hildemund',
  'Hildred',
  'Hildric',
  'Horst',
  'Hugo',
  'Igor',
  'Ingwald',
  'Jander',
  'Jekil',
  'Jodokus',
  'Johann',
  'Jonas',
  'Jorg',
  'Jorn',
  'Josef',
  'Jost',
  'Jurgen',
  'Karl',
  'Kaspar',
  'Klaus',
  'Kleber',
  'Konrad',
  'Konradin',
  'Kurt',
  'Lamprecht',
  'Lanfried',
  'Lanric',
  'Lanwin',
  'Leo',
  'Leopold',
  'Levin',
  'Liebert',
  'Liebrecht',
  'Liebwin',
  'Lienhart',
  'Linus',
  'Lodwig',
  'Lothar',
  'Lucius',
  'Ludwig',
  'Luitpold',
  'Lukas',
  'Lupold',
  'Lupus',
  'Luther',
  'Lutolf',
  'Madred',
  'Magnus',
  'Mandred',
  'Manfred',
  'Mathias',
  'Max',
  'Maximillian',
  'Meiner',
  'Meinhart',
  'Meinolf',
  'Mekel',
  'Merkel',
  'Nat',
  'Nathandar',
  'Nicodemus',
  'Odamar',
  'Odric',
  'Odwin',
  'Olbrecht',
  'Oldred',
  'Oldric',
  'Ortlieb',
  'Ortolf',
  'Orwin',
  'Oswald',
  'Osric',
  'Oswin',
  'Otfried',
  'Otto',
  'Otwin',
  'Paulus',
  'Prospero',
  'Ragen',
  'Ralf',
  'Rambrecht',
  'Randulf',
  'Ranulf',
  'Ranald',
  'Reikhard',
  'Rein',
  'Reiner',
  'Reinhard',
  'Reinolt',
  'Reuban',
  'Rigo',
  'Roderic',
  'Rolf',
  'Ruben',
  'Rudel',
  'Rudgar',
  'Rudolf',
  'Rufus',
  'Ruprecht',
  'Sebastian',
  'Semund',
  'Sepp',
  'Sieger',
  'Siegfried',
  'Siegmund',
  'Sigismund',
  'Sigric',
  'Steffan',
  'Tankred',
  'Theoderic',
  'Tilmann',
  'Tomas',
  'Trubald',
  'Trubert',
  'Udo',
  'Ulli',
  'Ulfred',
  'Ulfman',
  'Ulman',
  'Uto', 
  'Valdred',
  'Valdric',
  'Varl',
  'Viggo',
  'Viktor',
  'Vilmar',
  'Volker',
  'Volkhard',
  'Volkrad',
  'Volkin',
  'Voltz',
  'Walbrecht',
  'Waldor',
  'Waldred',
  'Walther',
  'Warmund',
  'Werner',
  'Wilbert',
  'Wilfried',
  'Wilhelm',
  'Woldred',
  'Wolfram',
  'Wolfhart',
  'Wolfgang',
  'Wulf',
  'Xavier'
]
# dwarf name = name1M/F + name2M/F
dwarf_name1_list = [
  'Al',
  'Ath',
  'Althran',
  'Bal',
  'Bala',
  'Bara',
  'Bel',
  'Bela',
  'Ber',
  'Bok',
  'Bor',
  'Bur',
  'Da',
  'Dam',
  'Dora',
  'Drok',
  'Drong',
  'Dur',
  'Dwal',
  'El',
  'Ela',
  'Elan',
  'Elda',
  'Fa',
  'Far',
  'Fara',
  'Fim',
  'Fima',
  'Firen',
  'Fur',
  'Fura',
  'Ga',
  'Gim',
  'Gol',
  'Gollen',
  'Got',
  'Gota',
  'Grim',
  'Gro',
  'Grun',
  'Hak',
  'Haka',
  'Har',
  'Hega',
  'Hur',
  'Kad',
  'Kar', 
  'Kata',
  'Kaz',
  'Kaza',
  'Krag',
  'Logaz',
  'Lok',
  'Lun',
  'Mo',
  'Mola',
  'Mor',
  'Mora',
  'No',
  'Nola',
  'Nor',
  'Noran',
  'Nun',
  'Oda',
  'Oka',
  'Olla',
  'Olf',
  'Oth',
  'Othra',
  'Ro',
  'Ror',
  'Roran',
  'Ska',
  'Skalla',
  'Skalf',
  'Skar',
  'Skor',
  'Skora',
  'Snor',
  'Snora',
  'Sven',
  'Thar',
  'Thor',
  'Thora',
  'Thron',
  'Thrun',
  'Thura',
  'Un',
  'Utha',
  'Ulla',
  'Vala',
  'Var',
  'Vara',
  'Zak',
  'Zaka',
  'Zakan',
  'Zar',
  'Zara',
  'Zam',
  'Zama'
]
dwarf_female_name2_list = [
  'bina',
  'bina',
  'bora',
  'bora',
  'dila',
  'dina',
  'dina',
  'dokina',
  'dokina',
  'dora',
  'dora',
  'drinella',
  'fina',
  'fina',
  'fya',
  'fya',
  'gana',
  'gana',
  'gara',
  'gara',
  'gella',
  'gella',
  'gina',
  'groma',
  'groma',
  'grondella',
  'grondella',
  'grotha',
  'grotha',
  'gruma',
  'gruma',
  'grunda',
  'grunda',
  'gruntina',
  'gruntina',
  'gona',
  'gora',
  'gora',
  'grimella',
  'grimella',
  'grina',
  'grina',
  'gromina',
  'gromina',
  'gula',
  'gunella',
  'gunella',
  'gundina',
  'gundina',
  'kina',
  'kina',
  'kragella',
  'kragella',
  'krina',
  'krina',
  'kya',
  'kya',
  'lina',
  'lina',
  'likina',
  'likina',
  'loka',
  'loka',
  'luna',
  'mina',
  'mina',
  'mira',
  'mira',
  'nina', 
  'nina',
  'nira',
  'nira',
  'nya',
  'ragina',
  'ragina',
  'riga',
  'riga',
  'riga',
  'rika',
  'rika',
  'rina',
  'rina',
  'runa',
  'runa',
  'runella',
  'runella',
  'skina',
  'skina',
  'skinella',
  'skinella',
  'tina',
  'toka',
  'trekella',
  'trekella',
  'trekina',
  'trekina',
  'troka',
  'troka',
  'zina',
  'zora'
]
dwarf_male_name2_list = [
  'bin',
  'bin',
  'bor',
  'bor',
  'dil',
  'din',
  'din',
  'dok',
  'dok',
  'dor',
  'dor',
  'drin',
  'drin',
  'fin',
  'fin',
  'gan',
  'gan',
  'gar',
  'gar',
  'gil',
  'gil',
  'gin',
  'gni',
  'gni',
  'grom',
  'grom',
  'grond',
  'grond',
  'groth',
  'groth',
  'grum',
  'grum',
  'grund',
  'grund',
  'grunt',
  'gon',
  'gon',
  'gor',
  'gor',
  'grim',
  'girm',
  'grin',
  'grin',
  'grom',
  'grom',
  'gul',
  'gul',
  'gun',
  'gun',
  'gund',
  'gund',
  'ki',
  'ki',
  'kin',
  'kin',
  'krag',
  'krag',
  'kri',
  'kri',
  'krin',
  'krin',
  'li',
  'li',
  'lin',
  'lin',
  'lik',
  'lik',
  'lok',
  'lok',
  'lun',
  'lun',
  'min',
  'min',
  'mir',
  'mir',
  'nin',
  'nin',
  'nir',
  'nir',
  'rag',
  'ri',
  'ri',
  'rig',
  'rig',
  'rik',
  'rik',
  'rin',
  'rin',
  'run',
  'run',
  'skin',
  'tin',
  'tin',
  'tok',
  'trek',
  'trok',
  'zin',
  'zor',
  'zor'
]
# elf name = name1 + connector(optional) + name2M/F
elf_name1_list = [
  'Aed',
  'Ael',
  'Aelf',
  'Aen',
  'Aeth',
  'Alth',
  'An',
  'And',
  'Ar',
  'Arg',
  'Ast',
  'Ath',
  'Av',
  'Ban',
  'Bel',
  'Beth',
  'Cad',
  'Cael',
  'Caem',
  'Caeth',
  'Cal',
  'Cam',
  'Cel',
  'Cir',
  'El',
  'Eld',
  'Elth',
  'En',
  'End',
  'Er',
  'Ers',
  'Fand',
  'Fer',
  'Ferg',
  'Fim',
  'Fin',
  'Gal',
  'Gald',
  'Gaen',
  'Gaes',
  'Ged',
  'Gen',
  'Ges',
  'Geth',
  'Glor',
  'Has',
  'Hath',
  'Hel',
  'Heth',
  'Hith',
  'Ill',
  'Ind',
  'Ist',
  'Ith',
  'Iy',
  'Kor',
  'Ky',
  'Kyr',
  'La',
  'Lan',
  'Lil',
  'Lim',
  'Lith',
  'Loth',
  'Mal',
  'Mar',
  'Mas',
  'Math',
  'Me',
  'Mes',
  'Meth',
  'Men',
  'Mor',
  'Mort',
  'Nal',
  'Nar',
  'Nen',
  'Nor',
  'Norl',
  'Ri',
  'Riabb',
  'Riann',
  'Rid',
  'Riell',
  'Rien',
  'Ruth',
  'Ryn',
  'Tab',
  'Tal',
  'Tan',
  'Tar',
  'Teth',
  'Tel',
  'Tor',
  'Ty',
  'Ul',
  'Um',
  'Ur',
  'Yr',
  'Yv'
]
elf_name_connector_list = [
  'a', 
  'al', 
  'an',
  'ar',
  'as',
  'e',
  'el',
  'en',
  'er',
  'es',
  'fan',
  'fen',
  'fin',
  'i',
  'il',
  'in',
  'ir',
  'is',
  'o',
  'ol',
  'on',
  'or',
  'os',
  'ra',
  'ral',
  'ran',
  're',
  'rel',
  'ren',
  'ri',
  'ril',
  'rin',
  'ro',
  'rol',
  'ron',
  'ry',
  'sa',
  'sal',
  'san',
  'se',
  'sel',
  'sen',
  'si',
  'sil',
  'sin',
  'so',
  'sol',
  'son',
  'u',
  'ul'
]
elf_male_name2_list = [
  'baen',
  'baine',
  'baire',
  'bar',
  'bhir',
  'brier',
  'brior',
  'brin',
  'daen',
  'daine',
  'daire',
  'dar',
  'dhil',
  'dhir',
  'drel',
  'drir',
  'dror',
  'eorl',
  'eos',
  'eoth',
  'fil',
  'fin',
  'fir',
  'hil',
  'hin',
  'hir',
  'hor',
  'il',
  'in',
  'ion',
  'ir',
  'is',
  'ith',
  'lael',
  'laen',
  'laer',
  'laine',
  'laire',
  'lan',
  'las',
  'len',
  'les',
  'lil',
  'lin',
  'lir',
  'lis',
  'lor',
  'los',
  'mael',
  'maen',
  'mair',
  'main',
  'mal',
  'mar',
  'mil',
  'min',
  'mir',
  'nael',
  'naen',
  'naer',
  'nail',
  'nair',
  'nal',
  'nan',
  'nar',
  'neal',
  'nean',
  'near',
  'nil',
  'nin',
  'nir',
  'nis',
  'ran',
  'rea',
  'rel',
  'ril',
  'riol',
  'rion',
  'rior',
  'riorl',
  'riorn',
  'rir',
  'ryel',
  'taen',
  'tair',
  'tain',
  'than',
  'thar',
  'thel',
  'thil',
  'thir',
  'thin',
  'thril',
  'thrin',
  'thwe',
  'til',
  'tin',
  'tis',
  'we',
  'yan'
]
elf_female_name2_list = [
  'a',
  'aine',
  'am',
  'ann',
  'arma',
  'arna',
  'arth',
  'ath',
  'beann',
  'bet',
  'beth',
  'brim',
  'brys',
  'deann',
  'det',
  'deth',
  'dys',
  'drian',
  'driel',
  'drys',
  'eann',
  'eanna',
  'earna',
  'earth',
  'elle',
  'eth',
  'eys',
  'eyth',
  'felle',
  'fionn',
  'flys',
  'fyll',
  'fynn',
  'fyr',
  'fys',
  'i',
  'ille',
  'ina',
  'ira',
  'isa',
  'ithi',
  'itt',
  'la',
  'lam',
  'lana',
  'larna',
  'lath',
  'leann',
  'leath',
  'lel',
  'lelle',
  'leth',
  'let',
  'lielle',
  'lieth',
  'lyann',
  'nelle',
  'nem',
  'neth',
  'ni',
  'niell',
  'nith',
  'ras',
  'reann',
  'rell',
  'relle',
  'rielle',
  'ris',
  'rith',
  'rys',
  'sar',
  'sath',
  'ser',
  'seth',
  'sir',
  'sith',
  'sor',
  'soth',
  'shar',
  'sher',
  'shir',
  'sys',
  'tar',
  'teal',
  'teann',
  'ter',
  'thea',
  'ther',
  'thi',
  'thryn',
  'thyn',
  'tir',
  'tor',
  'tos',
  'tryan',
  'trys',
  'yll',
  'yrs',
  'ys'
]
# halfling name = name1 + name2M/F
halfling_name1_list = [
  'Bag',
  'Balf',
  'Berc',
  'Bill',
  'Bobb',
  'Bodg',
  'Bog',
  'Bom',
  'Bonn',
  'Brog',
  'Bulc',
  'Bull',
  'Bust',
  'Cam',
  'Cap',
  'Ced',
  'Chund',
  'Clog',
  'Clof',
  'Cob',
  'Cog',
  'Crum',
  'Crump',
  'Curl',
  'Dod',
  'Dog',
  'Dott',
  'Dram',
  'Drub',
  'Drog',
  'Dron',
  'Durc',
  'Elm',
  'Enn',
  'Ermin',
  'Ethan', 
  'Falc',
  'Fald',
  'Falm',
  'Far',
  'Fild',
  'Flac',
  'Fogg',
  'Frit',
  'Ful',
  'Func',
  'Gaff',
  'Galb',
  'Gamm',
  'Gert',
  'Giff',
  'Gild',
  'Gon',
  'Grop',
  'Gudd',
  'Gump',
  'Ham',
  'Hal',
  'Hart',
  'Harp',
  'Jac',
  'Jas',
  'Jasp',
  'Joc',
  'Lac',
  'Lil',
  'Lob',
  'Lott',
  'Lud',
  'Lurc',
  'Mad',
  'Mag',
  'Man',
  'May',
  'Mer',
  'Mul',
  'Murc',
  'Murd',
  'Nag',
  'Nell',
  'Nobb',
  'Od',
  'Og',
  'Old',
  'Pipp',
  'Podd',
  'Porc',
  'Riff',
  'Rip',
  'Rob',
  'Sam',
  'Supp',
  'Taff',
  'Talb',
  'Talc',
  'Tay',
  'Tom',
  'Wald',
  'Watt',
  'Will'
]
halfling_male_name2_list = [
  'belly',
  'er',
  'fast',
  'in',
  'it',
  'mutch',
  'o',
  'odoc',
  'riadoc',
  'regar',
  'wick',
  'wise',
  'wit',
  'y'
]
halfling_female_name2_list = [
  'a',
  'adell',
  'alot',
  'apple',
  'bell',
  'berry',
  'eena',
  'ella',
  'era',
  'et',
  'ia',
  'flower',
  'lotta',
  'petal',
  'riella',
  'sweet',
  'trude',
  'rose',
  'willow',
  'y'
]
human_surname_list = [
  'Adelhof',
  'Albrecht',
  'Allenstag',
  'Altmann',
  'Atzwig',
  'Bacher',
  'Baer',
  'Baumann',
  'Becker',
  'Behn',
  'Betz',
  'Beyer',
  'Bischof',
  'Boehm',
  'Breitenbach',
  'Breuer',
  'Dahmbach',
  'Delfholt',
  'Drakenhof',
  'Drauwulf',
  'Durrbein',
  'Ehrhard',
  'Eisenhauer',
  'Eschlimann',
  'Falkenheim',
  'Fehr',
  'Fiegler',
  'Fleischer',
  'Frohlich',
  'Frueh',
  'Fuchs',
  'Gaffwig',
  'Gaertner',
  'Gebauer',
  'Godtgraf',
  'Grunenwald',
  'Guth',
  'Haintz',
  'Herz',
  'Herzog',
  'Hirtzel',
  'Hoch',
  'Hoefer',
  'Hofstetter',
  'Jaeger',
  'Jochutz',
  'Jutzenbach',
  'Kalb',
  'Kaltenbach',
  'Kraemer',
  'Krebs',
  'Kuhn',
  'Kummel',
  'Konig',
  'Konigsamen',
  'Lang',
  'Lankdorf',
  'Liess',
  'Lebengut',
  'Lutzen',
  'Machholt',
  'Meusmann',
  'Meyer',
  'Mohr',
  'Muller',
  'Nachtmann',
  'Naubhof',
  'Netzhoch',
  'Neumann',
  'Niederlitz',
  'Nuhr',
  'Oberholtzer',
  'Ohrsten',
  'Otzlowe',
  'Reichert',
  'Reifsneider',
  'Riese',
  'Rohrig',
  'Reiss',
  'Schaffer',
  'Schaumer',
  'Scherer',
  'Schultz',
  'Schleiermacher',
  'Schreiber',
  'Schwalb',
  'Steiner',
  'Tabbeck',
  'Teuber',
  'Tolzen',
  'Trachsel',
  'Weber',
  'Wechsler',
  'Wirtz',
  'Widmannn',
  'Widmer',
  'Veit',
  'Vogt',
  'Vogel',
  'Zumwald'
]
elf_surname_list = [
  'Białowłosy',
  'Błękit Pióra',
  'Błękit Skrzydła',
  'Błysk Klingi',
  'Błysk Pioruna',
  'Błysk Stali',
  'Bystrooki',
  'Ciemnowłosy',
  'Cienista Dolina',
  'Czarne Drzewo',
  'Czarny Kurhan',
  'Czysty Zdrój',
  'Dech Lasu',
  'Dębowy Konar',
  'Dotyk Nocy',
  'Dzikie Serce',
  'Gwiazda Wieczorna',
  'Gwiazda Zaranna',
  'Gwiezdne Oko',
  'Gwiezdny Ogień',
  'Gwiezdny Pył',
  'Jasna Gwiazda',
  'Jasnooki',
  'Jastrzębie Oko',
  'Jaśniejący',
  'Jeleni Skok',
  'Kieł Wilka',
  'Korona Słońca',
  'Krzyk Puchacza',
  'Księżycowy Blask',
  'Księżycowy Mrok',
  'Kwiat Młodości',
  'Lot Sokoła',
  'Lśniąca Góra',
  'Lśniący Grot',
  'Lśniący Księżyc',
  'Mądre Serce',
  'Mądrość Klanu',
  'Mężne Serce',
  'Młody Liść',
  'Moc Dębu',
  'Moc Korzeni',
  'Moc Różdżki',
  'Morska Fala',
  'Morska Piana',
  'Mroczne Ostrze',
  'Nocny Łowca',
  'Oko Wilka',
  'Oko Wizji',
  'Oko Zieleni',
  'Opadający Liść',
  'Opoka Siły',
  'Orzeł Mroku',
  'Ostre Ostrze',
  'Ostry Grot',
  'Pajęcza Nić',
  'Patrzący W Dal',
  'Podmuch Wichury',
  'Poranna Rosa',
  'Półksiężyc',
  'Promyk Słońca',
  'Przyjaciel Zwierząt',
  'Radosne Serce',
  'Różany Kwiat',
  'Ryk Burzy',
  'Silnoręki',
  'Smoczy Brat',
  'Smukłe Ostrze',
  'Smukły Grot',
  'Spokój Fal',
  'Spokój Kamienia',
  'Spokój Lasu',
  'Srebrnowłosy',
  'Srebrny Liść',
  'Srebrny Świt',
  'Strzała Mocy',
  'Szybki Grot',
  'Szybkie Ostrze',
  'Śnieżny Puch',
  'Śpiew Dzikości',
  'Śpiew Wiatru',
  'Ukryty W Cieniu',
  'Uśmiech Wiatru',
  'Wartki Strumyk',
  'Wędrowiec',
  'Wiatr Wśród Traw',
  'Wiatroskrzydły',
  'Wieża Mądrości',
  'Wodny Wir',
  'Wschodzące Słońce',
  'Wszechwidzący',
  'Wyniosły Dąb',
  'Wysoki Brzeg',
  'Zachodzące Słońce',
  'Zieleń Pióra',
  'Zieleń Skrzydła',
  'Zielona Dolina',
  'Złocisty Obłok',
  'Złota Struga',
  'Złotowłosy'
]
halfling_surname_list = [
  'Altannik',
  'Badylarz',
  'Beczułka',
  'Bielinek',
  'Brzeżek',
  'Brzuchacz',
  'Byliniak',
  'Cichobieg',
  'Cierniak',
  'Długonos',
  'Długouch',
  'Drapak',
  'Drewniak',
  'Dudziarz',
  'Dziwaczek',
  'Figlarz',
  'Futrzak',
  'Glistnik',
  'Głuptak',
  'Groszek',
  'Grzechotek',
  'Grzywacz',
  'Gwizdawek',
  'Iglarz',
  'Jabłecznik',
  'Jagódka',
  'Jaskółka',
  'Kaczeniec',
  'Kasztanek',
  'Kędziorek',
  'Kociak',
  'Kociołek',
  'Kogut',
  'Kolcownik',
  'Koniczynka',
  'Koralik',
  'Kosturek',
  'Kotlarz',
  'Kret',
  'Kręciołek',
  'Kruczek',
  'Krupnik',
  'Kulawik',
  'Kwietniak',
  'Łazik',
  'Łąkołaz',
  'Łodyżek',
  'Marudniak',
  'Mieszek',
  'Młynek',
  'Morwa',
  'Mroczek',
  'Niemysł',
  'Okruszek',
  'Opijus',
  'Otoczak',
  'Owsianniak',
  'Pagórek',
  'Paluch',
  'Piaszczak',
  'Piwniak',
  'Piwosz',
  'Podpłomyk',
  'Popiołek',
  'Przebiśnieg',
  'Radośnik',
  'Robaczek',
  'Rogaś',
  'Ryjek',
  'Rzęsawik',
  'Sknerus',
  'Skoblik',
  'Skórniak',
  'Słomnik',
  'Stoczek',
  'Stopowiąz',
  'Stopowłaz',
  'Sucharek',
  'Szarak',
  'Szarotek',
  'Śnieżynka',
  'Trzęsawiec',
  'Warkoczyk',
  'Wąsacz',
  'Wąwoźnik',
  'Wesołek',
  'Węgielek',
  'Wiatrownik',
  'Wierzbek',
  'Wietrzyk',
  'Wilczomlecz',
  'Wilkowyj',
  'Wodniak',
  'Wstążka',
  'Zagórnik',
  'Zawijas',
  'Zieleniak',
  'Złocisz',
  'Żarnik',
  'Żniwiarz'
]
# town_dict only contain typical birthplaces for human from The Empire
town_dict = {
  'Averland': {
    (1,25):'Averheim (stolica)', 
    (26,35): 'Grenzstadt (miasto)', 
    (36,45): 'Hochsleben (miasto)', 
    (46,54): 'Loningbruck (miasto)', 
    (55,63): 'Wuppertal (miasto)',
    (64,72): 'Agbeiten (wioska)',
    (73,81): 'Braundorf (wioska)',
    (82,91): 'Kotzenheim (wioska)',
    (92,100): 'Zecher (wioska)'
  },
  'Hochland': {
    (1,25): 'Hergig (stolica)', 
    (26,38): 'Breder (miasto)',
    (39,51): 'Krudenwald (miasto)',
    (52,64): 'Bergendorf (wioska)',
    (65,77): 'Esk (wioska)',
    (78,90): 'Gruyden (wioska)',
    (91,100): 'Koerin (wioska)'
  },
  'Middenland': {
    (1,25): 'Middenheim (stolica)', 
    (26,37): 'Delberz (miasto)', 
    (38,49): 'Grimminhagen (miasto)',
    (50,60): 'Norderingen (miasto)',
    (61,70): 'Holzbeck (wioska)',
    (71,80): 'Immelscheld (wioska)',
    (81,90): 'Pritzstock (wioska)',
    (91,100): 'Sokh (wioska)'
  },
  'Nordland': {
    (1,25): 'Salzenmund (stolica)',
    (26,38): 'Beeckerhoven (miasto)',
    (39,51): 'Dietershafen (miasto)',
    (52,64): 'Grafenrich (wioska)',
    (65,77): 'Luftberg (wioska)',
    (78,90): 'Oldenlitz (wioska)',
    (91,100): 'Wilhelmskoog (wioska)'
  },
  'Ostermark': {
    (1,25): 'Bechafen (stolica)',
    (26,38): 'Eisental (miasto)',
    (39,51): 'Remer (miasto)',
    (52,64): 'Bissendorf (wioska)',
    (65,77): 'Dorna (wioska)',
    (78,90): 'Fortenhaf (wioska)',
    (91,100): 'Heffengen (wioska)'
  },
  'Ostland': {
    (1,25): 'Wolfenburg (stolica)',
    (26,38): 'Ferlangen (miasto)',
    (39,51): 'Vandengart (miasto)',
    (52,64): 'Boven (wioska)',
    (65,77): 'Lubrecht (wioska)',
    (78,90): 'Smallhof (wioska)',
    (91,100): 'Zundap (wioska)',
  },
  'Reikland': {
    (1,25): 'Altdorf (stolica Imperium)',
    (26,40): 'Nuln (duże miasto)',
    (41,50): 'Bogenhafen (miasto)',
    (51,60): 'Grunburg (miasto)',
    (61,70): 'Halheim (wioska)',
    (71,80): 'Misthausen (wioska)',
    (81,90): 'Teufelfeuer (wioska)',
    (91,100): 'Weissbruck (wioska)'
  },
  'Stirland': {
    (1,25): 'Wurtbad (stolica)',
    (26,38): 'Drakenhof (miasto)',
    (39,51): 'Waldenhof (miasto)',
    (52,64): 'Eschedorf (wioska)',
    (65,77): 'Furtzhausen (wioska)',
    (78,90): 'Schwartzhafen',
    (91,100): 'Wurstheim',
  },
  'Talabekland': {
    (1,25): 'Talabheim (stolica)',
    (26,38): 'Bek (miasto)',
    (39,51): 'Kemperbad (miasto)',
    (52,64): 'Garndorf (wioska)',
    (65,77): 'Rangenhof (wioska)',
    (78,90): 'Wellenborn (wioska)',
    (91,100): 'Zurin (wioska)'
  },
  'Wissenland': {
    (1,25): 'Wissenburg (stolica)',
    (26,38): 'Grissenwald (miasto)',
    (39,51): 'Pfeildorf (miasto)',
    (52,64): 'Ambosstein (wioska)',
    (65,77): 'Konigsdorf (wioska)',
    (78,90): 'Segeldorf (wioska)',
    (91,100): 'Steingart (wioska)'
  }
}
dwarf_birthplace_list = [
  'Karak Norn (Góry Szare)',
  'Karak Izor (Przeskok)',
  'Karak Hirn (Góry Czarne)',
  'Karak Kadrin (Góry Krańca Świata)',
  'Karaz-a-Karak (Góry Krańca Świata)',
  'Zhufbar (Góry Krańca Świata)',
  'Bark Varr (Czarna Zatoka)'
]
elf_birthplace_dict = {
  (1,20): 'Altdorf',
  (21,40): 'Marienburg',
  (41,70): 'Las Laurelorn',
  (71,85): 'Wielki Las',
  (86,100): 'Las Reikwald'
}
